//! Vo Playground WASM - combines vo-web (system) and vogui (GUI library).

use std::cell::UnsafeCell;
use vo_common::vfs::MemoryFs;
use vo_web::{HostWaitKey, Vm};
use wasm_bindgen::prelude::*;

// Generated by build.rs from the selected local vogui workspace member.
include!(concat!(env!("OUT_DIR"), "/vogui_files.rs"));

#[cfg(test)]
#[path = "../build_support.rs"]
mod build_support;

const GUI_ENTRY_PATH: &str = "playground/app/main.vo";
const GUI_PROJECT_ROOT: &str = "playground/app";
const VOGUI_MEMBER_ROOT: &str = "playground/vogui";
const GUI_PROJECT_MOD: &str = include_str!("../gui_host/vo.mod");
const GUI_PROJECT_WORK: &str = include_str!("../gui_host/vo.work");

// =============================================================================
// Global State
// =============================================================================

struct GuiAppState {
    vm: Vm,
    /// Key of the main fiber's `waitForEvent` suspension (replay-style host event).
    event_wait_key: Option<HostWaitKey>,
}

thread_local! {
    static GUI_STATE: UnsafeCell<Option<GuiAppState>> = UnsafeCell::new(None);
}

/// Synchronize one JavaScript-side extension disposal with Rust routing state.
#[wasm_bindgen(js_name = "forgetWasmExtModuleOwner")]
pub fn forget_wasm_ext_module_owner(owner: &str) -> Result<(), JsValue> {
    vo_web::ext_bridge::forget_wasm_ext_module_owner(owner)
        .map(|_| ())
        .map_err(|error| js_sys::Error::new(&error).into())
}

/// Synchronize a JavaScript-side extension reset with Rust routing state.
#[wasm_bindgen(js_name = "clearWasmExtModuleOwners")]
pub fn clear_wasm_ext_module_owners() -> Result<(), JsValue> {
    vo_web::ext_bridge::clear_wasm_ext_state().map_err(|error| js_sys::Error::new(&error).into())
}

// =============================================================================
// Result Type
// =============================================================================

#[wasm_bindgen]
pub struct WasmGuiResult {
    status: String,
    render_bytes: Vec<u8>,
    error: String,
}

#[wasm_bindgen]
impl WasmGuiResult {
    #[wasm_bindgen(getter)]
    pub fn status(&self) -> String {
        self.status.clone()
    }

    #[wasm_bindgen(getter, js_name = "renderBytes")]
    pub fn render_bytes(&self) -> Vec<u8> {
        self.render_bytes.clone()
    }

    #[wasm_bindgen(getter)]
    pub fn error(&self) -> String {
        self.error.clone()
    }
}

impl WasmGuiResult {
    fn ok(render_bytes: Vec<u8>) -> Self {
        Self {
            status: "ok".into(),
            render_bytes,
            error: String::new(),
        }
    }

    fn err(msg: impl Into<String>) -> Self {
        Self {
            status: "error".into(),
            render_bytes: Vec::new(),
            error: msg.into(),
        }
    }

    fn compile_err(msg: impl Into<String>) -> Self {
        Self {
            status: "compile_error".into(),
            render_bytes: Vec::new(),
            error: msg.into(),
        }
    }
}

// =============================================================================
// WASM API
// =============================================================================

/// Initialize a GUI app from source code.
#[wasm_bindgen(js_name = "initGuiApp")]
pub fn init_gui_app(source: &str) -> WasmGuiResult {
    let local_fs = match build_gui_project_fs(source) {
        Ok(fs) => fs,
        Err(error) => return WasmGuiResult::compile_err(error),
    };
    let bytecode = match vo_web::compile_entry_with_mod_fs(
        GUI_ENTRY_PATH,
        local_fs,
        vo_web::build_stdlib_fs(),
        MemoryFs::new(),
    ) {
        Ok(b) => b,
        Err(e) => return WasmGuiResult::compile_err(e),
    };

    run_gui_bytecode(&bytecode, vo_web::ext_bridge::register_wasm_ext_bridges)
}

/// Initialize a GUI app from pre-compiled bytecode.
#[wasm_bindgen(js_name = "initGuiAppBytecode")]
pub fn init_gui_app_bytecode(bytecode: &[u8]) -> WasmGuiResult {
    run_gui_bytecode(bytecode, vo_web::ext_bridge::register_wasm_ext_bridges)
}

/// Handle a GUI event.
#[wasm_bindgen(js_name = "handleGuiEvent")]
pub fn handle_gui_event(handler_id: i32, payload: &str) -> WasmGuiResult {
    handle_event(handler_id, payload)
}

// =============================================================================
// Core Implementation
// =============================================================================

fn run_gui_bytecode(bytecode: &[u8], registrar: vo_web::ExternRegistrar) -> WasmGuiResult {
    GUI_STATE.with(|s| unsafe { *s.get() = None });

    let mut vm = match vo_web::create_vm(bytecode, registrar) {
        Ok(vm) => vm,
        Err(e) => return WasmGuiResult::err(e),
    };

    // Flush any user println output to console
    let stdout = vo_web::take_output();
    if !stdout.is_empty() {
        for line in stdout.lines() {
            if !line.is_empty() {
                web_sys::console::log_1(&format!("[Vo] {}", line).into());
            }
        }
    }

    // Read render bytes from VM host output channel
    let render_bytes = match vm.take_host_output() {
        Some(b) if !b.is_empty() => b,
        _ => return WasmGuiResult::err("No render output. emitRenderBinary was not called."),
    };

    // Find the replay-style host event token (waitForEvent suspension)
    let event_wait_key = select_gui_event_wait_key(
        vm.take_pending_host_events()
            .into_iter()
            .map(|event| event.key),
    );

    GUI_STATE.with(|s| unsafe {
        *s.get() = Some(GuiAppState { vm, event_wait_key });
    });

    WasmGuiResult::ok(render_bytes)
}

fn handle_event(handler_id: i32, payload: &str) -> WasmGuiResult {
    GUI_STATE.with(|s| {
        // SAFETY: WASM is single-threaded. JS-side busy guard prevents reentrant calls.
        let state = unsafe { &mut *s.get() };
        let state = match state.as_mut() {
            Some(st) => st,
            None => return WasmGuiResult::err("GUI app not initialized"),
        };

        state.vm.clear_host_output();
        vo_runtime::output::clear_output();

        // Encode event data: [i32 handler_id LE][UTF-8 payload]
        let key = match state.event_wait_key {
            Some(key) => key,
            None => return WasmGuiResult::err("Main fiber not waiting for events"),
        };
        let mut event_data = Vec::with_capacity(4 + payload.len());
        event_data.extend_from_slice(&handler_id.to_le_bytes());
        event_data.extend_from_slice(payload.as_bytes());

        if !state.vm.wake_host_event_with_data(key, event_data) {
            return WasmGuiResult::err("Host event wake was rejected by the VM");
        }
        if let Err(e) = state.vm.run_scheduled() {
            return WasmGuiResult::err(format!("{:?}", e));
        }

        // Flush any user println output to console
        let stdout = vo_web::take_output();
        if !stdout.is_empty() {
            for line in stdout.lines() {
                if !line.is_empty() {
                    web_sys::console::log_1(&format!("[Vo] {}", line).into());
                }
            }
        }

        // Update event_wait_key (waitForEvent re-suspends with a new key)
        state.event_wait_key = select_gui_event_wait_key(
            state
                .vm
                .take_pending_host_events()
                .into_iter()
                .map(|event| event.key),
        );

        // Read render bytes from VM host output channel
        let render_bytes = state.vm.take_host_output().unwrap_or_default();
        WasmGuiResult::ok(render_bytes)
    })
}

fn select_gui_event_wait_key(keys: impl IntoIterator<Item = HostWaitKey>) -> Option<HostWaitKey> {
    keys.into_iter()
        .find(|key| key.source.is_gui_event_replay())
}

fn build_gui_project_fs(source: &str) -> Result<MemoryFs, String> {
    let vogui_mod = std::str::from_utf8(VOGUI_MOD_FILE)
        .map_err(|error| format!("embedded vogui vo.mod is not UTF-8: {error}"))?;
    let mut fs = MemoryFs::new();
    fs.add_file(GUI_ENTRY_PATH, source);
    fs.add_file(format!("{GUI_PROJECT_ROOT}/vo.mod"), GUI_PROJECT_MOD);
    fs.add_file(format!("{GUI_PROJECT_ROOT}/vo.work"), GUI_PROJECT_WORK);
    fs.add_file(format!("{VOGUI_MEMBER_ROOT}/vo.mod"), vogui_mod);
    for (relative_path, bytes) in VOGUI_FILES {
        let content = std::str::from_utf8(bytes).map_err(|error| {
            format!("embedded vogui source {relative_path} is not UTF-8: {error}")
        })?;
        fs.add_file(format!("{VOGUI_MEMBER_ROOT}/{relative_path}"), content);
    }
    Ok(fs)
}

// Re-export vo-web functions (exposes them in the playground WASM JS API)
pub use vo_web::{compile_and_run, preload_ext_module, version, RunResult};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vogui_files_embedded() {
        const VOGUI_APP_PATH: &str = "playground/vogui/app.vo";

        assert!(VOGUI_FILES.len() > 0, "No .vo files embedded from vogui!");
        let has_app = VOGUI_FILES.iter().any(|(p, _)| *p == "app.vo");
        assert!(has_app, "app.vo not embedded");

        let fs = build_gui_project_fs("package main\nfunc main() {}\n").unwrap();

        use vo_common::vfs::FileSystem;
        assert!(fs.exists(std::path::Path::new("playground/app/vo.mod")));
        assert!(fs.exists(std::path::Path::new("playground/app/vo.work")));
        assert!(fs.exists(std::path::Path::new("playground/vogui/vo.mod")));
        assert!(!fs.exists(std::path::Path::new("playground/app/vo.lock")));
        assert!(
            fs.exists(std::path::Path::new(VOGUI_APP_PATH)),
            "{VOGUI_APP_PATH} not in fs"
        );
    }

    #[test]
    fn embedded_vogui_compiles_through_the_explicit_project_api() {
        let source = concat!(
            "package main\n",
            "import \"github.com/vo-lang/vogui\"\n",
            "func main() { _ = vogui.Text(\"ready\") }\n",
        );
        let bytecode = vo_web::compile_entry_with_mod_fs(
            GUI_ENTRY_PATH,
            build_gui_project_fs(source).unwrap(),
            vo_web::build_stdlib_fs(),
            MemoryFs::new(),
        )
        .expect("embedded all-local GUI workspace should compile without a registry lock");
        assert!(!bytecode.is_empty());
    }

    #[test]
    fn handle_event_reports_rejected_host_wake_043() {
        let key = HostWaitKey::decode("replay:42:4294967296:7").expect("valid host wait key");
        GUI_STATE.with(|state| unsafe {
            *state.get() = Some(GuiAppState {
                vm: Vm::new(),
                event_wait_key: Some(key),
            });
        });

        let result = handle_event(1, "{}");

        assert_eq!(result.status(), "error");
        assert!(
            result.error().contains("Host event wake was rejected"),
            "{}",
            result.error()
        );
    }

    #[test]
    fn handle_event_host_wake_records_only_gui_replay_wait_key_045() {
        let timer = HostWaitKey::decode("timer:1:4294967296:1").expect("valid timer wait key");
        let fetch = HostWaitKey::decode("replay-fetch:2:4294967297:2")
            .expect("valid fetch replay wait key");
        let gui = HostWaitKey::decode("replay-gui-event:3:4294967298:3")
            .expect("valid GUI replay wait key");
        let extension = HostWaitKey::decode("replay-extension:4:4294967299:4")
            .expect("valid extension replay wait key");

        assert_eq!(
            select_gui_event_wait_key([timer, fetch, gui, extension]),
            Some(gui),
            "the Playground GUI wake loop must select the GUI-event replay key"
        );
        assert_eq!(
            select_gui_event_wait_key([timer, fetch, extension]),
            None,
            "timer and non-GUI replay waits must not become the GUI event key"
        );
    }
}
