version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /lang/crates/vo-web
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: /eng/browser
    schedule:
      interval: weekly
      day: monday
      time: "03:20"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
