// The experimental wire has one schema for guest/host types and bounded codecs.
import assert from 'node:assert/strict';
import { generateCodecs } from './generate-codec.mjs';
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const args = process.argv.slice(2);
assert(args.length === 1 && ['--write', '--check'].includes(args[0]), 'usage: node eng/ui-next/generate.mjs --write|--check');
const sourcePath = 'ui/next/wire.schema.json';
const generatorPath = 'eng/ui-next/generate.mjs';
const codecInputs = ['eng/ui-next/generate-codec.mjs', 'eng/ui-next/codec.vo.txt', 'eng/ui-next/codec.ts.txt'];
const source = await readFile(resolve(root, sourcePath));
const schema = JSON.parse(source);
assert(Number.isSafeInteger(schema.version) && schema.version > 0 && schema.version < 256);
assert(schema.operations.every(op => /^[A-Za-z]+$/.test(op)));
assert.equal(new Set(schema.operations).size, schema.operations.length);
for (const value of Object.values(schema.limits)) assert(Number.isSafeInteger(value) && value > 0);
const primitive = { int: ['int', 'number'], float64: ['float64', 'number'], string: ['string', 'string'], bool: ['bool', 'boolean'], operation: ['string', 'Operation'] };
function types(type) {
  if (primitive[type]) return primitive[type];
  if (type.startsWith('*')) {
    assert(Object.hasOwn(schema.types, type.slice(1)), `unsupported wire type ${type}`);
    return [type, `${type.slice(1)} | null`];
  }
  assert(type.startsWith('[]') && (type.slice(2) === 'string' || Object.hasOwn(schema.types, type.slice(2))), `unsupported wire type ${type}`);
  return [type, `${type.slice(2)}[] | null`];
}
const banner = '// Generated by eng/ui-next/generate.mjs from ui/next/wire.schema.json. DO NOT EDIT.\n';
let vo = banner + 'package wire\n\n';
let ts = banner + `export const WIRE_VERSION = ${schema.version};\n`;
const constants = [['FRAME_BYTES', 'frameBytes'], ['MUTATIONS', 'mutations'], ['QUEUED_EVENTS', 'queuedEvents'], ['QUEUED_BYTES', 'queuedBytes'], ['EVENT_KEYS', 'eventKeys'], ['EVENT_KEY_BYTES', 'eventKeyBytes'], ['EVENT_MODIFIERS', 'eventModifiers'], ['SELECTED_VALUES', 'selectedValues'], ['PORTALS', 'portals']];
vo += `const Version = ${schema.version}\n\n`;
for (const [name, key] of constants) {
  ts += `export const MAX_${name} = ${schema.limits[key]};\n`;
  vo += `const Max${key[0].toUpperCase() + key.slice(1)} = ${schema.limits[key]}\n\n`;
}
assert(schema.eventKinds.every(kind => /^[a-z]+$/.test(kind)) && new Set(schema.eventKinds).size === schema.eventKinds.length);
ts += `export const EVENT_KINDS = ${JSON.stringify(schema.eventKinds)} as const;\n`;
function flags(definitions, voPrefix, tsPrefix) {
  let mask = 0;
  for (const [name, flag] of Object.entries(definitions)) {
    assert(/^[A-Z][A-Za-z]*$/.test(name) && Number.isSafeInteger(flag) && flag > 0 && flag < 256 && (flag & (flag - 1)) === 0 && !(mask & flag));
    mask |= flag;
    vo += `const ${voPrefix}${name} = ${flag}\n\n`;
    ts += `export const ${tsPrefix}_${name.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()} = ${flag};\n`;
  }
  return mask;
}
const eventMask = flags(schema.eventFlags, 'Event', 'EVENT');
ts += `export const EVENT_FLAGS_MASK = ${eventMask};\n`;
const modifierMask = flags(schema.keyModifiers, 'Key', 'KEY');
assert.equal(schema.limits.eventModifiers, 2 ** Object.keys(schema.keyModifiers).length);
ts += `export const KEY_MODIFIERS_MASK = ${modifierMask};\n`;
vo += `func ValidEventKind(kind string) bool {\n\tswitch kind {\n\t\tcase ${schema.eventKinds.map(kind => JSON.stringify(kind)).join(', ')}:\n\t\t\treturn true\n\t}\n\treturn false\n}\n\n`;
ts += `export type Operation = ${schema.operations.map(op => JSON.stringify(op)).join(' | ')};\n\n`;
for (const [index, name] of Object.keys(schema.types).entries()) {
  ts += `export const KIND_${name.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()} = ${index + 1};\n`;
}
for (const [name, fields] of Object.entries(schema.types)) {
  assert(/^[A-Z][A-Za-z0-9]*$/.test(name));
  const names = new Set(), jsonNames = new Set();
  vo += `type ${name} struct {\n`;
  ts += `export interface ${name} {\n`;
  for (const [field, type, json] of fields) {
    assert(/^[A-Z][A-Za-z0-9]*$/.test(field) && /^[a-z][A-Za-z0-9]*$/.test(json));
    assert(!names.has(field) && !jsonNames.has(json));
    names.add(field); jsonNames.add(json);
    const [voType, tsType] = types(type);
    vo += `\t${field} ${voType} \`json:"${json}"\`\n`;
    ts += `  ${json}: ${tsType};\n`;
  }
  vo += '}\n\n'; ts += '}\n\n';
}
const codec = await generateCodecs(schema, banner);
const outputs = new Map([
  ['ui/next/wire/wire.vo', vo.trimEnd() + '\n'],
  ['ui/next/wire/encode.vo', codec.vo.trimEnd() + '\n'],
  ['ui/next/wire/limits.rs', banner + `pub const MAX_FRAME_BYTES: usize = ${schema.limits.frameBytes};\n`],
  ['lang/crates/vo-web/js/ui_next/generated/protocol.ts', ts.trimEnd() + '\n'],
  ['lang/crates/vo-web/js/ui_next/generated/codec.ts', codec.ts.trimEnd() + '\n'],
]);
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const inputs = [sourcePath, generatorPath, ...codecInputs];
const sourceDigests = {};
for (const path of inputs) sourceDigests[path] = 'sha256:' + sha256(await readFile(resolve(root, path)));
for (const directory of ['ui/next/wire', 'lang/crates/vo-web/js/ui_next/generated']) {
  const files = [...outputs].filter(([path]) => path.startsWith(directory + '/')).map(([path, bytes]) => ({
    path: relative(directory, path), digest: 'sha256:' + sha256(bytes), size: Buffer.byteLength(bytes),
  }));
  outputs.set(`${directory}/provenance.json`, JSON.stringify({ schemaVersion: 2,
    artifact: directory === 'ui/next/wire' ? 'ui-next-wire.guest' : 'ui-next-wire.host', path: directory,
    generator: { command: ['node', generatorPath, '--write'], version: 1 },
    toolchain: { node: '>=24', format: `volang-ui-next-binary-v${schema.version}` },
    inputs, sourceDigests, outputs: files,
  }, null, 2) + '\n');
}
for (const [path, bytes] of outputs) {
  const absolute = resolve(root, path);
  if (args[0] === '--write') { await mkdir(dirname(absolute), { recursive: true }); await writeFile(absolute, bytes); }
  else assert.equal(await readFile(absolute, 'utf8'), bytes, `stale generated UI wire artifact: ${path}`);
}
console.log(`UI wire ${args[0] === '--write' ? 'generated' : 'verified'} (${outputs.size} files)`);
