//! io package native function implementations.

use vo_ffi_macro::vostd_errors;
use vo_runtime::bytecode::ExternDef;
use vo_runtime::ffi::ExternRegistry;

// IO sentinel errors - generated by vostd_errors! macro
vostd_errors! {
    "io" => {
        EOF => "EOF",
        UnexpectedEOF => "unexpected EOF",
        ShortWrite => "short write",
        ShortBuffer => "short buffer",
        NoProgress => "multiple Read calls return no data or error",
        ClosedPipe => "io: read/write on closed pipe",
        InvalidWrite => "invalid write result",
        Whence => "invalid whence",
        Offset => "invalid offset",
        NegativeRead => "negative read count",
        NegativeCount => "negative count",
    }
}

pub fn register_externs(registry: &mut ExternRegistry, externs: &[ExternDef]) {
    for (id, def) in externs.iter().enumerate() {
        let id = id as u32;
        match def.name.as_str() {
            "io_getIoErrors" => registry.register(id, get_io_errors),
            _ => {}
        }
    }
}
