//! io package native function implementations.

use vo_ffi_macro::vostd_errors;
use vo_runtime::bytecode::ExternDef;
use vo_runtime::ffi::{ExternRegistry, StdlibEntry};

// IO sentinel errors - generated by vostd_errors! macro
vostd_errors! {
    "io" => {
        EOF => "EOF",
        UnexpectedEOF => "unexpected EOF",
        ShortWrite => "short write",
        ShortBuffer => "short buffer",
        NoProgress => "multiple Read calls return no data or error",
        ClosedPipe => "io: read/write on closed pipe",
        InvalidRead => "invalid read result",
        InvalidWrite => "invalid write result",
        Whence => "invalid whence",
        Offset => "invalid offset",
        NegativeRead => "negative read count",
        NegativeCount => "negative count",
    }
}

#[doc(hidden)]
pub const REGISTERED_EXTERNS: &[StdlibEntry] = &[StdlibEntry {
    name: vo_runtime::vo_extern_name!("io", "getIoErrors"),
    func: get_io_errors,
    effects: vo_runtime::bytecode::ExternEffects::NONE,
}];

pub fn register_externs(
    registry: &mut ExternRegistry,
    externs: &[ExternDef],
) -> Result<(), vo_runtime::ffi::ExternContractError> {
    vo_runtime::ffi::register_stdlib_providers(registry, externs, REGISTERED_EXTERNS)
}
