//! Dynamic access runtime helpers for the ~> operator.
//!
//! Architecture:
//! - Layer 0: Common types (DynKey, DynErr)
//! - Layer 1: Protocol infrastructure
//! - Layer 2: Unified get_value/set_value
//! - Layer 3: Reflection handlers
//! - Layer 4: Call context and call/method
//! - Layer 5: Arg/return packing
//! - Layer 6: Extern entry points
//! - Layer 7: User API (dyn.GetAttr etc)

#[cfg(not(feature = "std"))]
use alloc::format;
#[cfg(not(feature = "std"))]
use alloc::vec;
#[cfg(not(feature = "std"))]
use alloc::vec::Vec;

use core::borrow::Borrow;

#[cfg(not(feature = "std"))]
use alloc::borrow::Cow;
#[cfg(feature = "std")]
use std::borrow::Cow;

use vo_common_core::types::{ValueKind, ValueRttid};
use vo_ffi_macro::vo_errors;

use super::error_helper::create_error_with_cause;
use crate::ffi::{ExternCallContext, ExternResult};
use crate::gc::{Gc, GcRef};
use crate::objects::{array, closure, interface, map, slice, string as str_obj};

// ============================================================================
// Layer 0: Error Types (generated by vo_errors! macro)
// ============================================================================

vo_errors! {
    internal "dyn" => {
        Unknown => "dynamic access: unknown error",
        NilBase => "dynamic access: base value is nil",
        BadField => "dynamic access: field does not exist",
        BadIndex => "dynamic access: invalid index type",
        OutOfBounds => "dynamic access: index out of bounds",
        BadCall => "dynamic access: cannot call value",
        SigMismatch => "dynamic access: signature mismatch",
        TypeMismatch => "dynamic access: type mismatch",
    }
}

// ============================================================================
// Layer 0: Common Types
// ============================================================================

/// Unified key for field or index access
enum DynKey<'a> {
    Field(&'a str),
    Index(u64, u64),
}

/// Internal error type (mirrors DynErrorKind but Copy)
#[derive(Clone, Copy)]
enum DynErr {
    NilBase,
    BadField,
    BadIndex,
    OutOfBounds,
    BadCall,
    SigMismatch,
    TypeMismatch,
}

impl From<DynErr> for DynErrorKind {
    fn from(e: DynErr) -> Self {
        match e {
            DynErr::NilBase => DynErrorKind::NilBase,
            DynErr::BadField => DynErrorKind::BadField,
            DynErr::BadIndex => DynErrorKind::BadIndex,
            DynErr::OutOfBounds => DynErrorKind::OutOfBounds,
            DynErr::BadCall => DynErrorKind::BadCall,
            DynErr::SigMismatch => DynErrorKind::SigMismatch,
            DynErr::TypeMismatch => DynErrorKind::TypeMismatch,
        }
    }
}

type DynResult<T> = Result<T, (DynErr, &'static str)>;

/// Error type that can carry either a DynErr or a CallClosure suspend request.
/// Used by helpers that need to call closures via the replay pattern.
enum DynOrSuspend {
    Dyn(DynErr, Cow<'static, str>),
    Suspend(ExternResult),
}

impl From<(DynErr, &'static str)> for DynOrSuspend {
    fn from((e, m): (DynErr, &'static str)) -> Self {
        DynOrSuspend::Dyn(e, Cow::Borrowed(m))
    }
}

type DynSuspendResult<T> = Result<T, DynOrSuspend>;

fn exact_replay_slots<const N: usize>(
    ret_vec: Vec<u64>,
    err: DynErr,
    context: &'static str,
) -> DynSuspendResult<[u64; N]> {
    if ret_vec.len() != N {
        return Err(DynOrSuspend::Dyn(
            err,
            Cow::Owned(format!(
                "{} replay returned {} slot(s), expected {}",
                context,
                ret_vec.len(),
                N
            )),
        ));
    }

    let mut ret = [0u64; N];
    ret.copy_from_slice(&ret_vec);
    Ok(ret)
}

/// Read `count` slots from a GcRef, returning zeros if the ref is null.
fn read_ref_slots(src_ref: GcRef, count: usize) -> Vec<u64> {
    (0..count)
        .map(|i| {
            if src_ref.is_null() {
                0
            } else {
                unsafe { Gc::read_slot(src_ref, i) }
            }
        })
        .collect()
}

// ============================================================================
// Layer 1: Protocol Infrastructure
// ============================================================================

/// Check if type implements a protocol interface.
fn check_protocol(
    call: &ExternCallContext,
    rttid: u32,
    vk: ValueKind,
    iface_id: Option<u32>,
) -> Option<u32> {
    let iface_id = iface_id?;
    let is_named = call.get_named_type_id_from_rttid(rttid, true).is_some();
    if is_named && call.check_interface_satisfaction(rttid, vk, iface_id) {
        Some(iface_id)
    } else {
        None
    }
}

/// Get func_id for a protocol method via itab lookup.
fn protocol_func_id(
    call: &mut ExternCallContext,
    rttid: u32,
    vk: ValueKind,
    iface_id: u32,
    err: DynErr,
) -> DynResult<u32> {
    let named_type_id = call
        .get_named_type_id_from_rttid(rttid, true)
        .ok_or((err, "type has no methods"))?;

    let src_is_pointer = vk == ValueKind::Pointer;
    let itab_id = call
        .try_get_or_create_itab(named_type_id, iface_id, src_is_pointer)
        .ok_or((err, "type does not implement protocol"))?;

    let itab = call.get_itab(itab_id).ok_or((err, "invalid itab"))?;

    itab.methods
        .first()
        .copied()
        .ok_or((err, "protocol has no methods"))
}

/// Build a Cow message from the replay panic context.
/// Returns Cow::Owned only when a real panic message is available; Cow::Borrowed otherwise.
fn replay_panic_cow(call: &ExternCallContext) -> Cow<'static, str> {
    match call.replay_panic_message() {
        Some(m) => Cow::Owned(format!("closure panicked: {}", m)),
        None => Cow::Borrowed("closure panicked"),
    }
}

/// Call a protocol method and check for error in return value.
/// Uses suspend/replay pattern: returns Suspend on first call, cached result on replay.
fn call_protocol<const N: usize>(
    call: &mut ExternCallContext,
    func_id: u32,
    args: &[u64],
    err: DynErr,
) -> DynSuspendResult<[u64; N]> {
    if call.is_replay_panicked() {
        let msg = replay_panic_cow(call);
        return Err(DynOrSuspend::Dyn(DynErr::BadCall, msg));
    }
    let ret_vec = match call.resume_closure_result() {
        Some(cached) => cached,
        None => {
            let closure_ref = closure::create(call.gc(), func_id, 0);
            return Err(DynOrSuspend::Suspend(ExternResult::CallClosure {
                closure_ref,
                args: args.to_vec(),
            }));
        }
    };

    let ret = exact_replay_slots(ret_vec, err, "dynamic protocol")?;

    // Error is always in last 2 slots
    let err_start = N.saturating_sub(2);
    if ret[err_start] != 0 || ret[err_start + 1] != 0 {
        return Err(DynOrSuspend::Dyn(
            err,
            Cow::Borrowed("protocol returned error"),
        ));
    }
    Ok(ret)
}

// ============================================================================
// Layer 2: Unified Get/Set
// ============================================================================

/// Get a value by field name or index. Returns (slot0, slot1) in interface format.
fn get_value(
    call: &mut ExternCallContext,
    base_slot0: u64,
    base_slot1: u64,
    key: DynKey,
) -> DynSuspendResult<(u64, u64)> {
    let vk = interface::unpack_value_kind(base_slot0);
    let rttid = interface::unpack_rttid(base_slot0);

    // Protocol check
    let protocol_id = match &key {
        DynKey::Field(_) => call.well_known().attr_object_iface_id,
        DynKey::Index(..) => call.well_known().index_object_iface_id,
    };
    if let Some(iface_id) = check_protocol(call, rttid, vk, protocol_id) {
        return get_via_protocol(call, base_slot1, rttid, vk, iface_id, &key);
    }

    // Reflection fallback
    get_reflection(call, base_slot0, base_slot1, rttid, vk, key).map_err(|e| e.into())
}

/// Set a value by field name or index.
fn set_value(
    call: &mut ExternCallContext,
    base_slot0: u64,
    base_slot1: u64,
    key: DynKey,
    val_slot0: u64,
    val_slot1: u64,
) -> DynSuspendResult<()> {
    let vk = interface::unpack_value_kind(base_slot0);
    let rttid = interface::unpack_rttid(base_slot0);

    // Protocol check
    let protocol_id = match &key {
        DynKey::Field(_) => call.well_known().set_attr_object_iface_id,
        DynKey::Index(..) => call.well_known().set_index_object_iface_id,
    };
    if let Some(iface_id) = check_protocol(call, rttid, vk, protocol_id) {
        return set_via_protocol(
            call, base_slot1, rttid, vk, iface_id, &key, val_slot0, val_slot1,
        );
    }

    // Reflection fallback
    set_reflection(
        call, base_slot0, base_slot1, rttid, vk, key, val_slot0, val_slot1,
    )
    .map_err(|e| e.into())
}

/// Get via protocol (AttrObject or IndexObject)
fn get_via_protocol(
    call: &mut ExternCallContext,
    base_slot1: u64,
    rttid: u32,
    vk: ValueKind,
    iface_id: u32,
    key: &DynKey,
) -> DynSuspendResult<(u64, u64)> {
    let err = match key {
        DynKey::Field(_) => DynErr::BadField,
        DynKey::Index(..) => DynErr::BadIndex,
    };
    let func_id = protocol_func_id(call, rttid, vk, iface_id, err)?;

    let ret = match key {
        DynKey::Field(name) => {
            let name_ref = call.alloc_str(name);
            call_protocol::<4>(call, func_id, &[base_slot1, name_ref as u64], err)?
        }
        DynKey::Index(k0, k1) => call_protocol::<4>(call, func_id, &[base_slot1, *k0, *k1], err)?,
    };
    Ok((ret[0], ret[1]))
}

/// Set via protocol (SetAttrObject or SetIndexObject)
#[allow(clippy::too_many_arguments)]
fn set_via_protocol(
    call: &mut ExternCallContext,
    base_slot1: u64,
    rttid: u32,
    vk: ValueKind,
    iface_id: u32,
    key: &DynKey,
    val_slot0: u64,
    val_slot1: u64,
) -> DynSuspendResult<()> {
    let err = match key {
        DynKey::Field(_) => DynErr::BadField,
        DynKey::Index(..) => DynErr::BadIndex,
    };
    let func_id = protocol_func_id(call, rttid, vk, iface_id, err)?;

    match key {
        DynKey::Field(name) => {
            let name_ref = call.alloc_str(name);
            call_protocol::<2>(
                call,
                func_id,
                &[base_slot1, name_ref as u64, val_slot0, val_slot1],
                err,
            )?;
        }
        DynKey::Index(k0, k1) => {
            call_protocol::<2>(
                call,
                func_id,
                &[base_slot1, *k0, *k1, val_slot0, val_slot1],
                err,
            )?;
        }
    };
    Ok(())
}

// ============================================================================
// Layer 3: Reflection Handlers
// ============================================================================

/// Get via reflection (built-in type handling)
fn get_reflection(
    call: &mut ExternCallContext,
    _base_slot0: u64,
    base_slot1: u64,
    rttid: u32,
    vk: ValueKind,
    key: DynKey,
) -> DynResult<(u64, u64)> {
    let base_ref = base_slot1 as GcRef;

    match (&key, vk) {
        // Field access on struct - try field first, then method
        (DynKey::Field(name), ValueKind::Struct) => {
            match get_struct_field(call, base_ref, rttid, name) {
                Ok(v) => Ok(v),
                Err(_) => get_method(call, rttid, vk, base_slot1, name),
            }
        }
        // Field access on pointer - try field first, then method
        (DynKey::Field(name), ValueKind::Pointer) => {
            let elem_rttid = call.get_elem_value_rttid_from_base(rttid).rttid();
            match get_struct_field(call, base_ref, elem_rttid, name) {
                Ok(v) => Ok(v),
                Err(_) => get_method(call, rttid, vk, base_slot1, name),
            }
        }
        // Field access on map (string key)
        (DynKey::Field(name), ValueKind::Map) => get_map_string_key(call, base_ref, rttid, name),
        // Index access on slice
        (DynKey::Index(k0, k1), ValueKind::Slice) => {
            get_slice_index(call, base_ref, rttid, *k0, *k1)
        }
        // Index access on array
        (DynKey::Index(k0, k1), ValueKind::Array) => {
            get_array_index(call, base_ref, rttid, *k0, *k1)
        }
        // Index access on string
        (DynKey::Index(k0, k1), ValueKind::String) => get_string_index(call, base_ref, *k0, *k1),
        // Index access on map
        (DynKey::Index(k0, k1), ValueKind::Map) => get_map_index(call, base_ref, rttid, *k0, *k1),
        // Field access on other types - try method lookup
        (DynKey::Field(name), _) => {
            if call.get_named_type_id_from_rttid(rttid, false).is_some() {
                get_method(call, rttid, vk, base_slot1, name)
            } else {
                Err((DynErr::TypeMismatch, "cannot access field on this type"))
            }
        }
        _ => Err((DynErr::TypeMismatch, "type does not support this access")),
    }
}

/// Set a value by field name or index.
#[allow(clippy::too_many_arguments)]
fn set_reflection(
    call: &mut ExternCallContext,
    _base_slot0: u64,
    base_slot1: u64,
    rttid: u32,
    vk: ValueKind,
    key: DynKey,
    val_slot0: u64,
    val_slot1: u64,
) -> DynResult<()> {
    let base_ref = base_slot1 as GcRef;

    match (&key, vk) {
        // Field set on struct/pointer
        (DynKey::Field(name), ValueKind::Struct) => {
            set_struct_field(call, base_ref, rttid, name, val_slot0, val_slot1)
        }
        (DynKey::Field(name), ValueKind::Pointer) => {
            let elem_rttid = call.get_elem_value_rttid_from_base(rttid).rttid();
            set_struct_field(call, base_ref, elem_rttid, name, val_slot0, val_slot1)
        }
        // Field set on map (string key)
        (DynKey::Field(name), ValueKind::Map) => {
            set_map_string_key(call, base_ref, rttid, name, val_slot0, val_slot1)
        }
        // Index set on slice
        (DynKey::Index(k0, k1), ValueKind::Slice) => {
            set_slice_index(call, base_ref, rttid, *k0, *k1, val_slot0, val_slot1)
        }
        // Index set on map
        (DynKey::Index(k0, k1), ValueKind::Map) => {
            set_map_index(call, base_ref, rttid, *k0, *k1, val_slot0, val_slot1)
        }
        // Cannot set on array/string (value types)
        (DynKey::Index(..), ValueKind::Array) => {
            Err((DynErr::TypeMismatch, "cannot set index on value-type array"))
        }
        (DynKey::Index(..), ValueKind::String) => {
            Err((DynErr::TypeMismatch, "cannot set index on string"))
        }
        _ => Err((
            DynErr::TypeMismatch,
            "type does not support this assignment",
        )),
    }
}

// ============================================================================
// Layer 3a: Struct Field Handlers
// ============================================================================

/// Recursive field lookup result
struct FieldInfo {
    offset: usize,
    slot_count: usize,
    rttid: u32,
    value_kind: ValueKind,
    ptr_derefs: Vec<PtrDeref>,
}

#[derive(Clone)]
struct PtrDeref {
    offset: u16,
}

fn lookup_field_recursive(
    call: &ExternCallContext,
    struct_meta_id: usize,
    field_name: &str,
    base_offset: usize,
    ptr_derefs: &mut Vec<PtrDeref>,
) -> Option<FieldInfo> {
    let meta = call.struct_meta(struct_meta_id)?;

    // Direct field match
    for field in &meta.fields {
        if field.name == field_name {
            let field_vk = field.type_info.value_kind();
            let field_rttid = field.type_info.rttid();
            return Some(FieldInfo {
                offset: base_offset + field.offset as usize,
                slot_count: field.slot_count as usize,
                rttid: field_rttid,
                value_kind: field_vk,
                ptr_derefs: ptr_derefs.clone(),
            });
        }
    }

    // Check embedded fields
    for field in &meta.fields {
        if !field.embedded {
            continue;
        }

        let embed_vk = field.type_info.value_kind();
        let embed_rttid = field.type_info.rttid();

        let (embed_struct_rttid, is_ptr) = if embed_vk == ValueKind::Pointer {
            (
                call.get_elem_value_rttid_from_base(embed_rttid).rttid(),
                true,
            )
        } else {
            (embed_rttid, false)
        };

        let embed_struct_meta_id = call.get_struct_meta_id_from_rttid(embed_struct_rttid)?;

        let new_base = if is_ptr {
            ptr_derefs.push(PtrDeref {
                offset: (base_offset + field.offset as usize) as u16,
            });
            0
        } else {
            base_offset + field.offset as usize
        };

        if let Some(result) = lookup_field_recursive(
            call,
            embed_struct_meta_id as usize,
            field_name,
            new_base,
            ptr_derefs,
        ) {
            return Some(result);
        }

        if is_ptr {
            ptr_derefs.pop();
        }
    }

    None
}

fn get_struct_field(
    call: &mut ExternCallContext,
    data_ref: GcRef,
    effective_rttid: u32,
    field_name: &str,
) -> DynResult<(u64, u64)> {
    let struct_meta_id = call
        .get_struct_meta_id_from_rttid(effective_rttid)
        .ok_or((DynErr::BadField, "not a struct type"))?;

    let mut ptr_derefs = Vec::new();
    let field = lookup_field_recursive(
        call,
        struct_meta_id as usize,
        field_name,
        0,
        &mut ptr_derefs,
    )
    .ok_or((DynErr::BadField, "field not found"))?;

    if data_ref.is_null() {
        return Err((DynErr::NilBase, "struct data is nil"));
    }

    // Follow pointer derefs
    let mut current_ref = data_ref;
    for deref in &field.ptr_derefs {
        let ptr_val = unsafe { Gc::read_slot(current_ref, deref.offset as usize) } as GcRef;
        if ptr_val.is_null() {
            return Err((DynErr::NilBase, "nil pointer in embedding path"));
        }
        current_ref = ptr_val;
    }

    // Read field data
    let raw_slots: Vec<u64> = (0..field.slot_count)
        .map(|i| unsafe { Gc::read_slot(current_ref, field.offset + i) })
        .collect();

    let boxed = call.box_to_interface(field.rttid, field.value_kind, &raw_slots);
    Ok((boxed.slot0, boxed.slot1))
}

fn set_struct_field(
    call: &mut ExternCallContext,
    data_ref: GcRef,
    effective_rttid: u32,
    field_name: &str,
    val_slot0: u64,
    val_slot1: u64,
) -> DynResult<()> {
    let struct_meta_id = call
        .get_struct_meta_id_from_rttid(effective_rttid)
        .ok_or((DynErr::BadField, "not a struct type"))?;

    let mut ptr_derefs = Vec::new();
    let field = lookup_field_recursive(
        call,
        struct_meta_id as usize,
        field_name,
        0,
        &mut ptr_derefs,
    )
    .ok_or((DynErr::BadField, "field not found"))?;

    if data_ref.is_null() {
        return Err((DynErr::NilBase, "struct data is nil"));
    }

    // Follow pointer derefs
    let mut current_ref = data_ref;
    for deref in &field.ptr_derefs {
        let ptr_val = unsafe { Gc::read_slot(current_ref, deref.offset as usize) } as GcRef;
        if ptr_val.is_null() {
            return Err((DynErr::NilBase, "embedded pointer is nil"));
        }
        current_ref = ptr_val;
    }

    // Unbox and write
    let field_vk = field.value_kind;
    let field_slots = field.slot_count;
    let field_slot_types: Vec<_> = {
        let parent_meta_id = Gc::header(current_ref).meta_id() as usize;
        let struct_meta = call
            .struct_meta(parent_meta_id)
            .ok_or((DynErr::BadField, "struct metadata missing"))?;
        let field_end = field
            .offset
            .checked_add(field_slots)
            .ok_or((DynErr::BadField, "field layout overflow"))?;
        struct_meta
            .slot_types
            .get(field.offset..field_end)
            .ok_or((DynErr::BadField, "field layout exceeds struct metadata"))?
            .to_vec()
    };
    let written_vals = prepare_dynamic_value_for_target(
        call,
        ValueRttid::new(field.rttid, field_vk),
        field_vk,
        field_slots,
        val_slot0,
        val_slot1,
        "dynamic struct field",
    )?;

    if !field_slot_types.is_empty() {
        crate::gc_types::typed_write_barrier(
            call.gc(),
            current_ref,
            &written_vals,
            &field_slot_types,
        );
    }
    for (i, &val) in written_vals.iter().enumerate() {
        unsafe {
            Gc::write_slot(current_ref, field.offset + i, val);
        }
    }

    Ok(())
}

// ============================================================================
// Layer 3b: Map Handlers
// ============================================================================

fn get_map_string_key(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    name: &str,
) -> DynResult<(u64, u64)> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot access field on nil map"));
    }

    let map_key_vk = map::key_kind(base_ref);
    if map_key_vk != ValueKind::String && map_key_vk != ValueKind::Interface {
        return Err((DynErr::BadField, "map key type is not string"));
    }

    let key_ref = call.alloc_str(name);
    let map_key_slots = map::key_slots(base_ref) as usize;
    let key_rttid = call.get_map_key_value_rttid_from_base(rttid);
    let string_rttid = call.find_basic_type_rttid(ValueKind::String);
    let key_slot0 = interface::pack_slot0(0, string_rttid, ValueKind::String);
    let key_data = prepare_dynamic_value_for_target(
        call,
        key_rttid,
        map_key_vk,
        map_key_slots,
        key_slot0,
        key_ref as u64,
        "dynamic map key",
    )
    .map_err(|_| (DynErr::BadField, "map key type mismatch"))?;
    let val_meta = map::val_meta(base_ref);
    let val_vk = val_meta.value_kind();
    let val_rttid = call.get_elem_value_rttid_from_base(rttid);

    let found = map::get_checked(base_ref, &key_data, Some(call.module()))
        .map_err(|_| (DynErr::BadField, "map key is not hashable"))?;

    // Dynamic access: missing key returns error (unlike Go's zero value)
    let val_slice = match found {
        Some(v) => v,
        None => return Err((DynErr::BadField, "map key not found")),
    };

    if val_vk == ValueKind::Interface {
        return Ok((val_slice[0], val_slice[1]));
    }

    let raw_slots: Vec<u64> = val_slice.to_vec();

    let boxed = call.box_to_interface(val_rttid.rttid(), val_vk, &raw_slots);
    Ok((boxed.slot0, boxed.slot1))
}

fn set_map_string_key(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    name: &str,
    val_slot0: u64,
    val_slot1: u64,
) -> DynResult<()> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot set field on nil map"));
    }

    let map_key_vk = map::key_kind(base_ref);
    if map_key_vk != ValueKind::String && map_key_vk != ValueKind::Interface {
        return Err((DynErr::BadField, "map key type is not string"));
    }

    let key_ref = call.alloc_str(name);
    let map_key_slots = map::key_slots(base_ref) as usize;
    let key_rttid = call.get_map_key_value_rttid_from_base(rttid);
    let string_rttid = call.find_basic_type_rttid(ValueKind::String);
    let key_slot0 = interface::pack_slot0(0, string_rttid, ValueKind::String);
    let key_data = prepare_dynamic_value_for_target(
        call,
        key_rttid,
        map_key_vk,
        map_key_slots,
        key_slot0,
        key_ref as u64,
        "dynamic map key",
    )?;
    let val_meta = map::val_meta(base_ref);
    let val_vk = val_meta.value_kind();
    let val_rttid = call.get_elem_value_rttid_from_base(rttid);
    let val_slots = checked_container_raw_slot_count(
        call,
        val_rttid,
        val_vk,
        map::val_slots(base_ref) as usize,
        "dynamic map value",
    )?;
    let val_data = prepare_dynamic_value_for_target(
        call,
        val_rttid,
        val_vk,
        val_slots,
        val_slot0,
        val_slot1,
        "dynamic map value",
    )?;

    call.typed_write_barrier_by_meta(base_ref, &key_data, map::key_meta(base_ref));
    if val_meta.value_kind().may_contain_gc_refs() {
        call.typed_write_barrier_by_meta(base_ref, &val_data, val_meta);
    }
    unsafe {
        // SAFETY: dynamic map writes applied key/value barriers above using map metadata.
        map::set_checked(base_ref, &key_data, &val_data, Some(call.module()))
    }
    .map_err(|err| match err {
        map::MapKeyError::UnhashableInterfaceKey => (DynErr::BadField, "map key is not hashable"),
        map::MapKeyError::SlotCountMismatch => (DynErr::TypeMismatch, "map entry layout mismatch"),
    })?;
    Ok(())
}

fn get_map_index(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    key_slot0: u64,
    key_slot1: u64,
) -> DynResult<(u64, u64)> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot index nil map"));
    }

    let map_key_vk = map::key_kind(base_ref);
    let map_key_slots = map::key_slots(base_ref) as usize;
    let key_rttid = call.get_map_key_value_rttid_from_base(rttid);
    let key_data = prepare_dynamic_value_for_target(
        call,
        key_rttid,
        map_key_vk,
        map_key_slots,
        key_slot0,
        key_slot1,
        "dynamic map key",
    )
    .map_err(|_| (DynErr::BadIndex, "map key type mismatch"))?;

    let val_meta = map::val_meta(base_ref);
    let val_vk = val_meta.value_kind();
    let val_rttid = call.get_elem_value_rttid_from_base(rttid);

    let found = map::get_checked(base_ref, &key_data, Some(call.module()))
        .map_err(|_| (DynErr::BadIndex, "map key is not hashable"))?;

    // Dynamic access: missing key returns error (unlike Go's zero value)
    let val_slice = match found {
        Some(v) => v,
        None => return Err((DynErr::BadField, "map key not found")),
    };

    if val_vk == ValueKind::Interface {
        return Ok((val_slice[0], val_slice[1]));
    }

    let raw_slots: Vec<u64> = val_slice.to_vec();

    let boxed = call.box_to_interface(val_rttid.rttid(), val_vk, &raw_slots);
    Ok((boxed.slot0, boxed.slot1))
}

fn set_map_index(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    key_slot0: u64,
    key_slot1: u64,
    val_slot0: u64,
    val_slot1: u64,
) -> DynResult<()> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot set index on nil map"));
    }

    let map_key_vk = map::key_kind(base_ref);
    let map_key_slots = map::key_slots(base_ref) as usize;
    let key_rttid = call.get_map_key_value_rttid_from_base(rttid);
    let key_data = prepare_dynamic_value_for_target(
        call,
        key_rttid,
        map_key_vk,
        map_key_slots,
        key_slot0,
        key_slot1,
        "dynamic map key",
    )
    .map_err(|_| (DynErr::BadIndex, "map key type mismatch"))?;

    let val_meta = map::val_meta(base_ref);
    let val_vk = val_meta.value_kind();
    let val_rttid = call.get_elem_value_rttid_from_base(rttid);
    let val_slots = checked_container_raw_slot_count(
        call,
        val_rttid,
        val_vk,
        map::val_slots(base_ref) as usize,
        "dynamic map value",
    )?;

    let val_data = prepare_dynamic_value_for_target(
        call,
        val_rttid,
        val_vk,
        val_slots,
        val_slot0,
        val_slot1,
        "dynamic map value",
    )?;

    let key_meta = map::key_meta(base_ref);
    if key_meta.value_kind().may_contain_gc_refs() {
        call.typed_write_barrier_by_meta(base_ref, &key_data, key_meta);
    }
    if val_meta.value_kind().may_contain_gc_refs() {
        call.typed_write_barrier_by_meta(base_ref, &val_data, val_meta);
    }
    unsafe {
        // SAFETY: dynamic map index writes applied key/value barriers above using map metadata.
        map::set_checked(base_ref, &key_data, &val_data, Some(call.module()))
    }
    .map_err(|err| match err {
        map::MapKeyError::UnhashableInterfaceKey => (DynErr::BadIndex, "map key is not hashable"),
        map::MapKeyError::SlotCountMismatch => (DynErr::TypeMismatch, "map entry layout mismatch"),
    })?;
    Ok(())
}

// ============================================================================
// Layer 3c: Slice/Array/String Index Handlers
// ============================================================================

/// Validates that the value implements the interface and computes the itab.
fn prepare_interface_value(
    call: &mut ExternCallContext,
    val_slot0: u64,
    val_slot1: u64,
    target_iface_meta_id: u32,
) -> DynResult<(u64, u64)> {
    if interface::is_nil(val_slot0) {
        return Ok((0, 0));
    }

    let val_vk = interface::unpack_value_kind(val_slot0);
    let val_rttid = interface::unpack_rttid(val_slot0);

    // For empty interface (any), meta_id is 0 - no itab needed
    if target_iface_meta_id == 0 {
        return Ok((val_slot0, val_slot1));
    }

    let named_type_id = call
        .get_named_type_id_from_rttid(val_rttid, true)
        .ok_or((DynErr::TypeMismatch, "value does not have methods"))?;
    let src_is_pointer = val_vk == ValueKind::Pointer;
    let itab_id = call
        .try_get_or_create_itab(named_type_id, target_iface_meta_id, src_is_pointer)
        .ok_or((DynErr::TypeMismatch, "value does not implement interface"))?;
    let stored_slot0 = interface::pack_slot0(itab_id, val_rttid, val_vk);
    Ok((stored_slot0, val_slot1))
}

enum IndexError {
    BadType,
    OutOfBounds,
}

fn check_int_index(key_slot0: u64, key_slot1: u64, len: usize) -> Result<usize, IndexError> {
    let key_vk = interface::unpack_value_kind(key_slot0);

    let idx: i64 = match key_vk {
        ValueKind::Int
        | ValueKind::Int8
        | ValueKind::Int16
        | ValueKind::Int32
        | ValueKind::Int64 => key_slot1 as i64,
        ValueKind::Uint
        | ValueKind::Uint8
        | ValueKind::Uint16
        | ValueKind::Uint32
        | ValueKind::Uint64 => key_slot1 as i64,
        _ => return Err(IndexError::BadType),
    };

    if idx < 0 || idx as usize >= len {
        return Err(IndexError::OutOfBounds);
    }
    Ok(idx as usize)
}

fn boxed_value_raw_slot_count(call: &ExternCallContext, rttid: u32, vk: ValueKind) -> usize {
    match vk {
        ValueKind::Interface => 2,
        ValueKind::Struct | ValueKind::Array => call.get_type_slot_count(rttid) as usize,
        _ => 1,
    }
}

fn checked_container_raw_slot_count(
    call: &ExternCallContext,
    value_rttid: ValueRttid,
    value_kind: ValueKind,
    physical_slots: usize,
    context: &'static str,
) -> DynResult<usize> {
    if value_rttid.value_kind() != value_kind {
        return Err((
            DynErr::TypeMismatch,
            match context {
                "dynamic map value" => "dynamic map value metadata kind mismatch",
                "dynamic slice element" => "dynamic slice element metadata kind mismatch",
                _ => "dynamic container metadata kind mismatch",
            },
        ));
    }
    let expected_slots = boxed_value_raw_slot_count(call, value_rttid.rttid(), value_kind);
    if expected_slots != physical_slots {
        return Err((
            DynErr::TypeMismatch,
            match context {
                "dynamic map value" => "dynamic map value layout mismatch",
                "dynamic slice element" => "dynamic slice element layout mismatch",
                _ => "dynamic container layout mismatch",
            },
        ));
    }
    Ok(physical_slots)
}

fn nil_assignable_to_value_kind(value_kind: ValueKind) -> bool {
    matches!(
        value_kind,
        ValueKind::Interface
            | ValueKind::Pointer
            | ValueKind::Slice
            | ValueKind::Map
            | ValueKind::Closure
            | ValueKind::Channel
            | ValueKind::Port
            | ValueKind::Island
    )
}

#[cfg(test)]
fn validate_dynamic_container_value_type(value_kind: ValueKind, val_slot0: u64) -> DynResult<()> {
    if value_kind == ValueKind::Interface {
        return Ok(());
    }
    if interface::is_nil(val_slot0) {
        if nil_assignable_to_value_kind(value_kind) {
            return Ok(());
        }
        return Err((
            DynErr::TypeMismatch,
            "cannot write nil to non-nillable container value",
        ));
    }
    let src_val_vk = interface::unpack_value_kind(val_slot0);
    if value_kind != src_val_vk {
        return Err((DynErr::TypeMismatch, "container value type mismatch"));
    }
    Ok(())
}

fn dynamic_value_requires_exact_rttid(value_kind: ValueKind) -> bool {
    matches!(
        value_kind,
        ValueKind::Struct
            | ValueKind::Array
            | ValueKind::Slice
            | ValueKind::Map
            | ValueKind::Channel
            | ValueKind::Closure
            | ValueKind::Pointer
            | ValueKind::Port
            | ValueKind::Island
    )
}

fn dynamic_integer_value_kind(value_kind: ValueKind) -> bool {
    matches!(
        value_kind,
        ValueKind::Int
            | ValueKind::Int8
            | ValueKind::Int16
            | ValueKind::Int32
            | ValueKind::Int64
            | ValueKind::Uint
            | ValueKind::Uint8
            | ValueKind::Uint16
            | ValueKind::Uint32
            | ValueKind::Uint64
    )
}

fn coerce_dynamic_integer_slot(target_kind: ValueKind, raw: u64) -> Option<u64> {
    match target_kind {
        ValueKind::Int8 => Some((raw as i8) as i64 as u64),
        ValueKind::Int16 => Some((raw as i16) as i64 as u64),
        ValueKind::Int32 => Some((raw as i32) as i64 as u64),
        ValueKind::Int64 => Some(raw as i64 as u64),
        #[cfg(target_pointer_width = "32")]
        ValueKind::Int => Some((raw as i32) as i64 as u64),
        #[cfg(target_pointer_width = "64")]
        ValueKind::Int => Some(raw as i64 as u64),
        ValueKind::Uint8 => Some((raw as u8) as u64),
        ValueKind::Uint16 => Some((raw as u16) as u64),
        ValueKind::Uint32 => Some((raw as u32) as u64),
        ValueKind::Uint64 => Some(raw),
        #[cfg(target_pointer_width = "32")]
        ValueKind::Uint => Some((raw as u32) as u64),
        #[cfg(target_pointer_width = "64")]
        ValueKind::Uint => Some(raw),
        _ => None,
    }
}

fn read_boxed_array_value_slots(
    call: &ExternCallContext,
    array_ref: GcRef,
    target_rttid: ValueRttid,
    target_slots: usize,
) -> DynResult<Vec<u64>> {
    if array_ref.is_null() {
        return Err((DynErr::TypeMismatch, "dynamic array value is nil"));
    }
    let array_len = call.get_array_len_from_rttid(target_rttid.rttid());
    let elem_rttid = call.get_elem_value_rttid_from_base(target_rttid.rttid());
    let elem_vk = elem_rttid.value_kind();
    let elem_bytes = array::elem_bytes(array_ref);
    let elem_slots = checked_sequence_elem_raw_slot_count(call, elem_rttid, elem_vk, elem_bytes)?;
    let expected_slots = elem_slots
        .checked_mul(array_len)
        .ok_or((DynErr::TypeMismatch, "dynamic array value layout overflow"))?;
    if expected_slots != target_slots {
        return Err((DynErr::TypeMismatch, "dynamic array value layout mismatch"));
    }

    let mut raw_slots = vec![0u64; target_slots];
    for idx in 0..array_len {
        let start = idx * elem_slots;
        let end = start + elem_slots;
        read_array_elem_logical_slots(
            array_ref,
            idx,
            elem_vk,
            elem_bytes,
            &mut raw_slots[start..end],
        );
    }
    Ok(raw_slots)
}

fn read_boxed_aggregate_value_slots(
    call: &ExternCallContext,
    target_rttid: ValueRttid,
    target_kind: ValueKind,
    target_slots: usize,
    value_ref: GcRef,
) -> DynResult<Vec<u64>> {
    if value_ref.is_null() {
        return Err((DynErr::TypeMismatch, "dynamic aggregate value is nil"));
    }
    match target_kind {
        ValueKind::Struct => Ok(read_ref_slots(value_ref, target_slots)),
        ValueKind::Array => {
            read_boxed_array_value_slots(call, value_ref, target_rttid, target_slots)
        }
        _ => Err((DynErr::TypeMismatch, "dynamic target is not aggregate")),
    }
}

fn prepare_dynamic_value_for_target(
    call: &mut ExternCallContext,
    target_rttid: ValueRttid,
    target_kind: ValueKind,
    target_slots: usize,
    val_slot0: u64,
    val_slot1: u64,
    context: &'static str,
) -> DynResult<Vec<u64>> {
    if target_rttid.value_kind() != target_kind {
        return Err((DynErr::TypeMismatch, "dynamic target metadata mismatch"));
    }

    if interface::is_nil(val_slot0) {
        if target_kind == ValueKind::Interface {
            return Ok(vec![0; target_slots]);
        }
        if nil_assignable_to_value_kind(target_kind) {
            return Ok(vec![0; target_slots]);
        }
        return Err((DynErr::TypeMismatch, "cannot write nil to dynamic target"));
    }

    if target_kind == ValueKind::Interface {
        let iface_meta_id = call
            .get_interface_meta_id_from_rttid(target_rttid.rttid())
            .ok_or((
                DynErr::TypeMismatch,
                "dynamic interface target metadata missing",
            ))?;
        let (slot0, slot1) = prepare_interface_value(call, val_slot0, val_slot1, iface_meta_id)?;
        return Ok(vec![slot0, slot1]);
    }

    let src_kind = interface::unpack_value_kind(val_slot0);
    if dynamic_integer_value_kind(target_kind) {
        if !dynamic_integer_value_kind(src_kind) || target_slots != 1 {
            return Err((DynErr::TypeMismatch, "dynamic target value kind mismatch"));
        }
        let Some(coerced) = coerce_dynamic_integer_slot(target_kind, val_slot1) else {
            return Err((DynErr::TypeMismatch, "dynamic integer target mismatch"));
        };
        return Ok(vec![coerced]);
    }
    if src_kind != target_kind {
        return Err((DynErr::TypeMismatch, "dynamic target value kind mismatch"));
    }
    let src_rttid = interface::unpack_rttid(val_slot0);
    if dynamic_value_requires_exact_rttid(target_kind) && src_rttid != target_rttid.rttid() {
        return Err((DynErr::TypeMismatch, "dynamic target runtime type mismatch"));
    }

    if matches!(target_kind, ValueKind::Struct | ValueKind::Array) {
        read_boxed_aggregate_value_slots(
            call,
            target_rttid,
            target_kind,
            target_slots,
            val_slot1 as GcRef,
        )
    } else if target_slots == 0 {
        Ok(Vec::new())
    } else if target_slots == 1 {
        Ok(vec![val_slot1])
    } else {
        let raw_slots = read_ref_slots(val_slot1 as GcRef, target_slots);
        if raw_slots.len() != target_slots {
            return Err((DynErr::TypeMismatch, context));
        }
        Ok(raw_slots)
    }
}

fn checked_sequence_elem_raw_slot_count(
    call: &ExternCallContext,
    elem_rttid: ValueRttid,
    elem_vk: ValueKind,
    elem_bytes: usize,
) -> DynResult<usize> {
    if elem_rttid.value_kind() != elem_vk {
        return Err((
            DynErr::TypeMismatch,
            "dynamic sequence element metadata kind mismatch",
        ));
    }
    let expected_slots = boxed_value_raw_slot_count(call, elem_rttid.rttid(), elem_vk);
    let physical_slots = elem_bytes.div_ceil(8);

    if elem_bytes == 0 {
        if elem_vk == ValueKind::Struct && expected_slots == 1 {
            return Ok(expected_slots);
        }
    } else if physical_slots == expected_slots {
        return Ok(expected_slots);
    }

    Err((
        DynErr::TypeMismatch,
        "dynamic sequence element layout mismatch",
    ))
}

fn sequence_elem_raw_slots<F>(
    call: &ExternCallContext,
    elem_rttid: ValueRttid,
    elem_vk: ValueKind,
    elem_bytes: usize,
    read_elem: F,
) -> DynResult<Vec<u64>>
where
    F: FnOnce(&mut [u64]),
{
    let expected_slots =
        checked_sequence_elem_raw_slot_count(call, elem_rttid, elem_vk, elem_bytes)?;
    let mut raw_slots = vec![0u64; expected_slots];
    if elem_bytes != 0 {
        read_elem(&mut raw_slots);
    }
    Ok(raw_slots)
}

fn read_array_elem_logical_slots(
    array_ref: GcRef,
    idx: usize,
    elem_vk: ValueKind,
    elem_bytes: usize,
    dst: &mut [u64],
) {
    if elem_bytes == 0 {
        return;
    }
    if dst.len() == 1 && elem_bytes <= 8 {
        dst[0] = unsafe { array::get_auto(array_ref, idx, elem_bytes) };
    } else {
        unsafe { array::get_n(array_ref, idx, dst, elem_bytes) };
    }
    let _ = elem_vk;
}

fn read_slice_elem_logical_slots(
    slice_ref: GcRef,
    idx: usize,
    elem_vk: ValueKind,
    elem_bytes: usize,
    dst: &mut [u64],
) {
    if elem_bytes == 0 {
        return;
    }
    if dst.len() == 1 && elem_bytes <= 8 {
        dst[0] = unsafe { slice::get_auto(slice::data_ptr(slice_ref), idx, elem_bytes, elem_vk) };
    } else {
        unsafe { slice::get_n(slice_ref, idx, dst, elem_bytes) };
    }
}

fn write_slice_elem_raw_slots(base_ref: GcRef, idx: usize, elem_bytes: usize, raw_slots: &[u64]) {
    if elem_bytes == 0 {
        return;
    }
    unsafe { slice::set_n(base_ref, idx, raw_slots, elem_bytes) };
}

fn get_slice_index(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    key_slot0: u64,
    key_slot1: u64,
) -> DynResult<(u64, u64)> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot index nil slice"));
    }

    let len = slice::len(base_ref);
    let idx = check_int_index(key_slot0, key_slot1, len).map_err(|e| match e {
        IndexError::BadType => (DynErr::BadIndex, "index must be integer"),
        IndexError::OutOfBounds => (DynErr::OutOfBounds, "slice index out of bounds"),
    })?;

    let elem_meta = slice::elem_meta(base_ref);
    let elem_vk = elem_meta.value_kind();
    let elem_rttid = call.get_elem_value_rttid_from_base(rttid);
    let elem_bytes = array::elem_bytes(slice::array_ref(base_ref));
    let raw_slots = sequence_elem_raw_slots(call, elem_rttid, elem_vk, elem_bytes, |dst| {
        read_slice_elem_logical_slots(base_ref, idx, elem_vk, elem_bytes, dst);
    })?;

    let boxed = call.box_to_interface(elem_rttid.rttid(), elem_vk, &raw_slots);
    Ok((boxed.slot0, boxed.slot1))
}

fn set_slice_index(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    key_slot0: u64,
    key_slot1: u64,
    val_slot0: u64,
    val_slot1: u64,
) -> DynResult<()> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot set index on nil slice"));
    }

    let len = slice::len(base_ref);
    let idx = check_int_index(key_slot0, key_slot1, len).map_err(|e| match e {
        IndexError::BadType => (DynErr::BadIndex, "index must be integer"),
        IndexError::OutOfBounds => (DynErr::OutOfBounds, "slice index out of bounds"),
    })?;

    let elem_meta = slice::elem_meta(base_ref);
    let elem_vk = elem_meta.value_kind();
    let elem_rttid = call.get_elem_value_rttid_from_base(rttid);
    let elem_bytes = array::elem_bytes(slice::array_ref(base_ref));
    let elem_slots = checked_sequence_elem_raw_slot_count(call, elem_rttid, elem_vk, elem_bytes)?;

    let written_vals = prepare_dynamic_value_for_target(
        call,
        elem_rttid,
        elem_vk,
        elem_slots,
        val_slot0,
        val_slot1,
        "dynamic slice element",
    )?;

    if elem_meta.value_kind().may_contain_gc_refs() {
        let arr_ref = slice::array_ref(base_ref);
        call.typed_write_barrier_by_meta(arr_ref, &written_vals, elem_meta);
    }
    write_slice_elem_raw_slots(base_ref, idx, elem_bytes, &written_vals);

    Ok(())
}

fn get_array_index(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    rttid: u32,
    key_slot0: u64,
    key_slot1: u64,
) -> DynResult<(u64, u64)> {
    if base_ref.is_null() {
        return Err((DynErr::NilBase, "cannot index nil array"));
    }

    let len = array::len(base_ref);
    let idx = check_int_index(key_slot0, key_slot1, len).map_err(|e| match e {
        IndexError::BadType => (DynErr::BadIndex, "index must be integer"),
        IndexError::OutOfBounds => (DynErr::OutOfBounds, "array index out of bounds"),
    })?;

    let elem_meta = array::elem_meta(base_ref);
    let elem_vk = elem_meta.value_kind();
    let elem_bytes = array::elem_bytes(base_ref);
    let elem_rttid = call.get_elem_value_rttid_from_base(rttid);
    let raw_slots = sequence_elem_raw_slots(call, elem_rttid, elem_vk, elem_bytes, |dst| {
        read_array_elem_logical_slots(base_ref, idx, elem_vk, elem_bytes, dst);
    })?;

    let boxed = call.box_to_interface(elem_rttid.rttid(), elem_vk, &raw_slots);
    Ok((boxed.slot0, boxed.slot1))
}

fn get_string_index(
    call: &mut ExternCallContext,
    base_ref: GcRef,
    key_slot0: u64,
    key_slot1: u64,
) -> DynResult<(u64, u64)> {
    let s = str_obj::as_str(base_ref);
    let bytes = s.as_bytes();

    let idx = check_int_index(key_slot0, key_slot1, bytes.len()).map_err(|e| match e {
        IndexError::BadType => (DynErr::BadIndex, "index must be integer"),
        IndexError::OutOfBounds => (DynErr::OutOfBounds, "string index out of bounds"),
    })?;

    let boxed = call.box_to_interface(
        ValueKind::Uint8 as u32,
        ValueKind::Uint8,
        &[bytes[idx] as u64],
    );
    Ok((boxed.slot0, boxed.slot1))
}

// ============================================================================
// Layer 3d: Method Lookup
// ============================================================================

fn get_method(
    call: &mut ExternCallContext,
    rttid: u32,
    vk: ValueKind,
    receiver_slot1: u64,
    method_name: &str,
) -> DynResult<(u64, u64)> {
    let method_info = call
        .lookup_method(rttid, method_name)
        .ok_or((DynErr::BadField, "method not found"))?;
    let func_id = method_info.func_id;
    let recv_slots = call
        .get_func_def(func_id)
        .ok_or((DynErr::BadCall, "method function metadata missing"))?
        .recv_slots as usize;
    let captures = method_receiver_captures(vk, receiver_slot1, &method_info, recv_slots)?;

    let closure_ref = closure::create(call.gc(), func_id, captures.len());
    for (idx, slot) in captures.into_iter().enumerate() {
        // Safety: `closure_ref` is freshly allocated; it is marked for
        // scanning after all captures are initialized.
        unsafe { closure::set_capture(closure_ref, idx, slot) };
    }
    call.gc().mark_allocated_for_scan(closure_ref);

    let slot0 = interface::pack_slot0(0, method_info.signature_rttid, ValueKind::Closure);
    Ok((slot0, closure_ref as u64))
}

fn method_receiver_captures(
    vk: ValueKind,
    receiver_slot1: u64,
    method_info: &vo_common_core::bytecode::MethodInfo,
    recv_slots: usize,
) -> DynResult<Vec<u64>> {
    method_info
        .iface_receiver_slot_type_for_source_kind(vk)
        .map_err(|_| {
            (
                DynErr::BadCall,
                "method receiver layout does not match dynamic source",
            )
        })?;
    if recv_slots == 0 {
        return Ok(Vec::new());
    }
    if recv_slots == 1 {
        // NamedTypeMeta.methods exposes interface ABI targets: pointer receivers use the
        // original one-slot pointer receiver, and value receivers use a $iface wrapper that
        // expects the interface data slot. In both cases the whole receiver is slot1.
        return Ok(vec![receiver_slot1]);
    }
    if method_info.is_pointer_receiver {
        return Err((DynErr::BadCall, "pointer receiver method must use one slot"));
    }
    if vk == ValueKind::Struct || vk == ValueKind::Array || vk == ValueKind::Pointer {
        let receiver_ref = receiver_slot1 as GcRef;
        if receiver_ref.is_null() {
            return Err((DynErr::NilBase, "method receiver is nil"));
        }
        return Ok(read_ref_slots(receiver_ref, recv_slots));
    }
    Err((DynErr::BadCall, "method receiver layout is unsupported"))
}

// ============================================================================
// Layer 4: Call Helpers
// ============================================================================

fn call_return_error(
    call: &mut ExternCallContext,
    error_offset: u16,
    err: DynErr,
    msg: &str,
) -> ExternResult {
    for i in 0..error_offset {
        call.ret_u64(i, 0);
    }
    let (cause0, cause1) = dyn_sentinel_error(call, err.into());
    let pair = create_error_with_cause(call, msg, cause0, cause1);
    call.ret_interface_pair(error_offset, pair);
    ExternResult::Ok
}

fn call_return_success(call: &mut ExternCallContext, error_offset: u16) -> ExternResult {
    call.ret_nil(error_offset);
    call.ret_nil(error_offset + 1);
    ExternResult::Ok
}

fn get_expected_meta(
    call: &ExternCallContext,
    metas_start: u16,
    is_any_start: u16,
    i: usize,
) -> (u32, ValueKind, bool) {
    let meta_raw = call.arg_u64(metas_start + i as u16) as u32;
    let is_any = call.arg_u64(is_any_start + i as u16) != 0;
    let rttid = meta_raw >> 8;
    let vk = ValueKind::from_u8((meta_raw & 0xFF) as u8);
    (rttid, vk, is_any)
}

fn compute_error_offset(
    call: &ExternCallContext,
    ret_count: usize,
    metas_start: u16,
    is_any_start: u16,
) -> u16 {
    let mut offset: u16 = 0;
    for i in 0..ret_count {
        let meta_raw = call.arg_u64(metas_start + i as u16) as u32;
        let is_any = call.arg_u64(is_any_start + i as u16) != 0;
        let rttid = meta_raw >> 8;
        let vk = ValueKind::from_u8((meta_raw & 0xFF) as u8);
        let width = match vk {
            ValueKind::Interface => 2,
            ValueKind::Struct | ValueKind::Array => call.get_type_slot_count(rttid) as usize,
            _ => 1,
        };
        offset += output_slot_count(is_any, vk, width);
    }
    offset
}

fn output_slot_count(is_any: bool, vk: ValueKind, width: usize) -> u16 {
    if is_any || ((vk == ValueKind::Struct || vk == ValueKind::Array) && width > 2) {
        2
    } else {
        width.min(2) as u16
    }
}

// ============================================================================
// Layer 4: Call/Method Implementation
// ============================================================================

#[allow(clippy::too_many_arguments)]
fn do_call(
    call: &mut ExternCallContext,
    closure_ref: GcRef,
    sig_rttid: u32,
    args_slice_ref: GcRef,
    ret_count: usize,
    metas_start: u16,
    is_any_start: u16,
    error_offset: u16,
) -> ExternResult {
    if call.is_replay_panicked() {
        let msg = replay_panic_cow(call);
        return call_return_error(call, error_offset, DynErr::BadCall, &msg);
    }
    if closure_ref.is_null() {
        return call_return_error(call, error_offset, DynErr::BadCall, "closure is null");
    }

    // Get function signature
    let (params, ret_value_rttids, is_variadic) = match call.get_func_signature(sig_rttid) {
        Some((p, r, v)) => (p.clone(), r.clone(), v),
        None => {
            return call_return_error(
                call,
                error_offset,
                DynErr::BadCall,
                "invalid closure signature",
            );
        }
    };

    // Check return count
    let actual_ret_count = ret_value_rttids.len();
    if ret_count != actual_ret_count {
        let msg = format!(
            "return count mismatch: expected {} return value(s), function returns {} (hint: adjust LHS variable count to match function signature)",
            ret_count, actual_ret_count
        );
        return call_return_error(call, error_offset, DynErr::SigMismatch, &msg);
    }

    // Check parameter count
    let arg_count = if args_slice_ref.is_null() {
        0
    } else {
        slice::len(args_slice_ref)
    };
    let expected_params = if is_variadic && !params.is_empty() {
        params.len() - 1
    } else {
        params.len()
    };

    if !is_variadic && arg_count != expected_params {
        let msg = format!(
            "parameter count mismatch: expected {}, got {}",
            expected_params, arg_count
        );
        return call_return_error(call, error_offset, DynErr::SigMismatch, &msg);
    }
    if is_variadic && arg_count < expected_params {
        let msg = format!(
            "parameter count mismatch: expected at least {}, got {}",
            expected_params, arg_count
        );
        return call_return_error(call, error_offset, DynErr::SigMismatch, &msg);
    }

    // Unpack args
    let args = match unpack_args(call, args_slice_ref, &params, is_variadic) {
        Ok(a) => a,
        Err(_) => {
            return call_return_error(
                call,
                error_offset,
                DynErr::SigMismatch,
                "argument type mismatch",
            );
        }
    };

    // Call closure via suspend/replay
    let ret_buffer = match call.resume_closure_result() {
        Some(cached) => cached,
        None => {
            return ExternResult::CallClosure { closure_ref, args };
        }
    };
    let expected_ret_slots = replay_return_slot_count(call, &ret_value_rttids);
    if ret_buffer.len() != expected_ret_slots {
        let msg = format!(
            "closure replay returned {} slot(s), expected {}",
            ret_buffer.len(),
            expected_ret_slots
        );
        return call_return_error(call, error_offset, DynErr::BadCall, &msg);
    }

    // Pack returns
    if let Err(msg) = pack_returns(
        call,
        &ret_buffer,
        &ret_value_rttids,
        ret_count,
        metas_start,
        is_any_start,
        error_offset,
    ) {
        return call_return_error(call, error_offset, DynErr::BadCall, &msg);
    }
    call_return_success(call, error_offset)
}

#[allow(clippy::too_many_arguments)]
fn do_method(
    call: &mut ExternCallContext,
    base_slot0: u64,
    base_slot1: u64,
    method_name: &str,
    args_slice_ref: GcRef,
    ret_count: usize,
    metas_start: u16,
    is_any_start: u16,
    error_offset: u16,
) -> ExternResult {
    let vk = interface::unpack_value_kind(base_slot0);
    let rttid = interface::unpack_rttid(base_slot0);

    // Try protocol first
    let closure = if let Some(iface_id) =
        check_protocol(call, rttid, vk, call.well_known().attr_object_iface_id)
    {
        match get_method_via_protocol(call, base_slot1, rttid, vk, iface_id, method_name) {
            Ok(c) => Some(c),
            Err(DynOrSuspend::Dyn(e, m)) => {
                return call_return_error(call, error_offset, e, m.borrow());
            }
            Err(DynOrSuspend::Suspend(r)) => return r,
        }
    } else {
        None
    };

    // Fallback to reflection
    let (closure_slot0, closure_slot1) = if let Some(c) = closure {
        c
    } else {
        match get_method(call, rttid, vk, base_slot1, method_name) {
            Ok(c) => c,
            Err((e, m)) => return call_return_error(call, error_offset, e, m),
        }
    };

    // Verify it's a closure
    let closure_vk = interface::unpack_value_kind(closure_slot0);
    if closure_vk != ValueKind::Closure {
        return call_return_error(
            call,
            error_offset,
            DynErr::BadCall,
            &format!("{} is not a method", method_name),
        );
    }

    let closure_rttid = interface::unpack_rttid(closure_slot0);
    let closure_ref = closure_slot1 as GcRef;

    do_call(
        call,
        closure_ref,
        closure_rttid,
        args_slice_ref,
        ret_count,
        metas_start,
        is_any_start,
        error_offset,
    )
}

fn get_method_via_protocol(
    call: &mut ExternCallContext,
    base_slot1: u64,
    rttid: u32,
    vk: ValueKind,
    iface_id: u32,
    method_name: &str,
) -> DynSuspendResult<(u64, u64)> {
    let func_id = protocol_func_id(call, rttid, vk, iface_id, DynErr::BadField)?;
    let name_ref = call.alloc_str(method_name);
    let ret = call_protocol::<4>(
        call,
        func_id,
        &[base_slot1, name_ref as u64],
        DynErr::BadField,
    )?;
    Ok((ret[0], ret[1]))
}

// ============================================================================
// Layer 5: Arg/Return Packing
// ============================================================================

fn unpack_args(
    call: &mut ExternCallContext,
    args_slice_ref: GcRef,
    params: &[vo_common_core::types::ValueRttid],
    is_variadic: bool,
) -> Result<Vec<u64>, ()> {
    let mut args = Vec::new();

    if args_slice_ref.is_null() {
        return Ok(args);
    }

    let arg_count = slice::len(args_slice_ref);
    let elem_bytes = array::elem_bytes(slice::array_ref(args_slice_ref));
    let non_variadic_count = if is_variadic && !params.is_empty() {
        params.len() - 1
    } else {
        params.len()
    };

    // Unpack non-variadic args
    for (i, param) in params
        .iter()
        .enumerate()
        .take(non_variadic_count.min(arg_count))
    {
        let param_vk = param.value_kind();
        let param_slots = call.get_type_slot_count(param.rttid()) as usize;

        let (arg_slot0, arg_slot1) = read_slice_elem(args_slice_ref, i, elem_bytes);
        let raw_arg = prepare_dynamic_value_for_target(
            call,
            *param,
            param_vk,
            param_slots,
            arg_slot0,
            arg_slot1,
            "dynamic call argument",
        )
        .map_err(|_| ())?;
        args.extend(raw_arg);
    }

    // Handle variadic
    if is_variadic && !params.is_empty() {
        let variadic_param = params.last().unwrap();
        let variadic_slice_rttid = variadic_param.rttid();

        let elem_vr = match call.get_slice_elem(variadic_slice_rttid) {
            Some(vr) => vr,
            None => return Ok(args),
        };
        let elem_vk = elem_vr.value_kind();
        let elem_slots = call.get_type_slot_count(elem_vr.rttid()) as usize;
        let elem_meta = call.value_meta_for_value_rttid(elem_vr);

        let variadic_count = arg_count.saturating_sub(non_variadic_count);
        if variadic_count == 0 {
            args.push(core::ptr::null::<u8>() as u64);
        } else {
            let new_slice = slice::create(
                call.gc(),
                elem_meta,
                elem_slots * 8,
                variadic_count,
                variadic_count,
            );
            for i in 0..variadic_count {
                let (arg_slot0, arg_slot1) =
                    read_slice_elem(args_slice_ref, non_variadic_count + i, elem_bytes);
                let raw_arg = prepare_dynamic_value_for_target(
                    call,
                    elem_vr,
                    elem_vk,
                    elem_slots,
                    arg_slot0,
                    arg_slot1,
                    "dynamic variadic argument",
                )
                .map_err(|_| ())?;
                write_slice_elem_raw_slots(new_slice, i, elem_slots * 8, &raw_arg);
            }
            if elem_meta.value_kind().may_contain_gc_refs() {
                call.gc()
                    .mark_allocated_for_scan(slice::array_ref(new_slice));
            }
            args.push(new_slice as u64);
        }
    }

    Ok(args)
}

fn read_slice_elem(slice_ref: GcRef, idx: usize, elem_bytes: usize) -> (u64, u64) {
    let base_ptr = slice::data_ptr(slice_ref);
    let elem_ptr = unsafe { base_ptr.add(idx * elem_bytes) };
    let slot0 = unsafe { *(elem_ptr as *const u64) };
    let slot1 = if elem_bytes >= 16 {
        unsafe { *((elem_ptr as *const u64).add(1)) }
    } else {
        0
    };
    (slot0, slot1)
}

fn replay_value_slot_width(
    call: &ExternCallContext,
    vr: &vo_common_core::types::ValueRttid,
) -> usize {
    match vr.value_kind() {
        ValueKind::Interface => 2,
        ValueKind::Struct | ValueKind::Array => call.get_type_slot_count(vr.rttid()) as usize,
        _ => 1,
    }
}

fn replay_return_slot_count(
    call: &ExternCallContext,
    ret_value_rttids: &[vo_common_core::types::ValueRttid],
) -> usize {
    ret_value_rttids
        .iter()
        .map(|vr| replay_value_slot_width(call, vr))
        .sum()
}

fn pack_returns(
    call: &mut ExternCallContext,
    ret_buffer: &[u64],
    ret_value_rttids: &[vo_common_core::types::ValueRttid],
    ret_count: usize,
    metas_start: u16,
    is_any_start: u16,
    _error_offset: u16,
) -> Result<(), Cow<'static, str>> {
    let mut src_off = 0usize;
    let mut dst_off: u16 = 0;

    for i in 0..ret_count {
        let (_expected_rttid, expected_vk, is_any) =
            get_expected_meta(call, metas_start, is_any_start, i);

        let vr = ret_value_rttids.get(i).ok_or_else(|| {
            Cow::Owned(format!(
                "missing return metadata for dynamic result {} of {}",
                i, ret_count
            ))
        })?;
        let actual_rttid = vr.rttid();
        let actual_vk = vr.value_kind();
        let actual_width = replay_value_slot_width(call, vr);

        let raw_slots = ret_buffer
            .get(src_off..src_off + actual_width)
            .ok_or_else(|| {
                Cow::Owned(format!(
                    "closure replay returned too few slots for dynamic result {}: need slots {}..{}, buffer has {}",
                    i,
                    src_off,
                    src_off + actual_width,
                    ret_buffer.len()
                ))
            })?;
        src_off += actual_width;

        let output_slots = output_slot_count(is_any, expected_vk, actual_width);

        if is_any {
            let boxed = call.box_to_interface(actual_rttid, actual_vk, raw_slots);
            call.ret_any(dst_off, boxed);
        } else if (expected_vk == ValueKind::Struct || expected_vk == ValueKind::Array)
            && actual_width > 2
        {
            let boxed = call.box_to_interface(actual_rttid, actual_vk, raw_slots);
            call.ret_u64(dst_off, 0);
            call.ret_u64(dst_off + 1, boxed.slot1);
        } else {
            if output_slots > 0 {
                call.ret_u64(dst_off, raw_slots[0]);
            }
            if output_slots > 1 {
                call.ret_u64(dst_off + 1, raw_slots[1]);
            }
        }

        dst_off += output_slots;
    }

    if src_off != ret_buffer.len() {
        return Err(Cow::Owned(format!(
            "closure replay returned {} extra slot(s)",
            ret_buffer.len() - src_off
        )));
    }

    Ok(())
}

// ============================================================================
// Layer 6: Extern Entry Points
// ============================================================================

fn dyn_field(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let field_name_ref = call.arg_ref(2);
    let expected_rttid = call.arg_u64(3) as u32;
    let expected_vk = ValueKind::from_u8(call.arg_u64(4) as u8);

    if interface::is_nil(base_slot0) {
        return write_get_error(call, DynErr::NilBase, "cannot access field on nil");
    }

    let field_name = if field_name_ref.is_null() {
        return write_get_error(call, DynErr::NilBase, "field name is nil");
    } else {
        str_obj::as_str(field_name_ref)
    };

    match get_value(call, base_slot0, base_slot1, DynKey::Field(field_name)) {
        Ok((v0, v1)) => write_get_result(call, v0, v1, expected_rttid, expected_vk),
        Err(DynOrSuspend::Dyn(e, m)) => write_get_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_index(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let key_slot0 = call.arg_u64(2);
    let key_slot1 = call.arg_u64(3);
    let expected_rttid = call.arg_u64(4) as u32;
    let expected_vk = ValueKind::from_u8(call.arg_u64(5) as u8);

    if interface::is_nil(base_slot0) {
        return write_get_error(call, DynErr::NilBase, "cannot index nil");
    }

    match get_value(
        call,
        base_slot0,
        base_slot1,
        DynKey::Index(key_slot0, key_slot1),
    ) {
        Ok((v0, v1)) => write_get_result(call, v0, v1, expected_rttid, expected_vk),
        Err(DynOrSuspend::Dyn(e, m)) => write_get_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_set_field(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let field_name_ref = call.arg_ref(2);
    let val_slot0 = call.arg_u64(3);
    let val_slot1 = call.arg_u64(4);

    if interface::is_nil(base_slot0) {
        return write_set_error(call, DynErr::NilBase, "cannot set field on nil");
    }

    let field_name = if field_name_ref.is_null() {
        return write_set_error(call, DynErr::NilBase, "field name is nil");
    } else {
        str_obj::as_str(field_name_ref)
    };

    match set_value(
        call,
        base_slot0,
        base_slot1,
        DynKey::Field(field_name),
        val_slot0,
        val_slot1,
    ) {
        Ok(()) => {
            call.ret_nil(0);
            call.ret_nil(1);
            ExternResult::Ok
        }
        Err(DynOrSuspend::Dyn(e, m)) => write_set_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_set_index_unified(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let key_slot0 = call.arg_u64(2);
    let key_slot1 = call.arg_u64(3);
    let val_slot0 = call.arg_u64(4);
    let val_slot1 = call.arg_u64(5);

    if interface::is_nil(base_slot0) {
        return write_set_error(call, DynErr::NilBase, "cannot set index on nil");
    }

    match set_value(
        call,
        base_slot0,
        base_slot1,
        DynKey::Index(key_slot0, key_slot1),
        val_slot0,
        val_slot1,
    ) {
        Ok(()) => {
            call.ret_nil(0);
            call.ret_nil(1);
            ExternResult::Ok
        }
        Err(DynOrSuspend::Dyn(e, m)) => write_set_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_call(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let args_slice_ref = call.arg_u64(2) as GcRef;
    let ret_count = call.arg_u64(3) as usize;
    let metas_start = 4u16;
    let is_any_start = metas_start + ret_count as u16;
    let error_offset = compute_error_offset(call, ret_count, metas_start, is_any_start);

    if interface::is_nil(base_slot0) {
        return call_return_error(call, error_offset, DynErr::NilBase, "cannot call nil");
    }

    let vk = interface::unpack_value_kind(base_slot0);
    let rttid = interface::unpack_rttid(base_slot0);

    // Protocol check
    if let Some(iface_id) = check_protocol(call, rttid, vk, call.well_known().call_object_iface_id)
    {
        return do_call_via_protocol(
            call,
            base_slot1,
            rttid,
            vk,
            iface_id,
            args_slice_ref,
            ret_count,
            metas_start,
            is_any_start,
            error_offset,
        );
    }

    // Closure fallback
    if vk != ValueKind::Closure {
        return call_return_error(
            call,
            error_offset,
            DynErr::BadCall,
            &format!("cannot call {:?}", vk),
        );
    }

    do_call(
        call,
        base_slot1 as GcRef,
        rttid,
        args_slice_ref,
        ret_count,
        metas_start,
        is_any_start,
        error_offset,
    )
}

fn dyn_method(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let method_name_ref = call.arg_u64(2) as GcRef;
    let args_slice_ref = call.arg_u64(3) as GcRef;
    let ret_count = call.arg_u64(4) as usize;
    let metas_start = 5u16;
    let is_any_start = metas_start + ret_count as u16;
    let error_offset = compute_error_offset(call, ret_count, metas_start, is_any_start);

    if interface::is_nil(base_slot0) {
        return call_return_error(
            call,
            error_offset,
            DynErr::NilBase,
            "cannot call method on nil",
        );
    }

    let method_name = str_obj::as_str(method_name_ref);
    do_method(
        call,
        base_slot0,
        base_slot1,
        method_name,
        args_slice_ref,
        ret_count,
        metas_start,
        is_any_start,
        error_offset,
    )
}

#[allow(clippy::too_many_arguments)]
fn do_call_via_protocol(
    call: &mut ExternCallContext,
    base_slot1: u64,
    rttid: u32,
    vk: ValueKind,
    iface_id: u32,
    args_slice_ref: GcRef,
    ret_count: usize,
    metas_start: u16,
    is_any_start: u16,
    error_offset: u16,
) -> ExternResult {
    // Protocol only supports single return
    if ret_count > 1 {
        return call_return_error(
            call,
            error_offset,
            DynErr::SigMismatch,
            "CallObject only supports single return",
        );
    }

    let func_id = match protocol_func_id(call, rttid, vk, iface_id, DynErr::BadCall) {
        Ok(id) => id,
        Err((e, m)) => return call_return_error(call, error_offset, e, m),
    };

    if call.is_replay_panicked() {
        let msg = replay_panic_cow(call);
        return call_return_error(call, error_offset, DynErr::BadCall, &msg);
    }

    let closure_ref = closure::create(call.gc(), func_id, 0);
    let args = vec![base_slot1, args_slice_ref as u64];

    let ret_vec = match call.resume_closure_result() {
        Some(cached) => cached,
        None => {
            return ExternResult::CallClosure { closure_ref, args };
        }
    };

    let ret = match exact_replay_slots::<4>(ret_vec, DynErr::BadCall, "CallObject protocol") {
        Ok(ret) => ret,
        Err(DynOrSuspend::Dyn(e, m)) => return call_return_error(call, error_offset, e, &m),
        Err(DynOrSuspend::Suspend(r)) => return r,
    };

    // Check error
    if ret[2] != 0 || ret[3] != 0 {
        for i in 0..error_offset {
            call.ret_u64(i, 0);
        }
        call.ret_interface_pair(error_offset, (ret[2], ret[3]));
        return ExternResult::Ok;
    }

    // Unbox result
    if ret_count == 0 {
        return call_return_success(call, error_offset);
    }

    let (_expected_rttid, expected_vk, is_any) =
        get_expected_meta(call, metas_start, is_any_start, 0);
    if is_any || expected_vk == ValueKind::Interface {
        call.ret_u64(0, ret[0]);
        call.ret_u64(1, ret[1]);
    } else {
        call.ret_u64(0, ret[1]);
    }

    call_return_success(call, error_offset)
}

// ============================================================================
// Layer 6a: Result Writers
// ============================================================================

fn write_get_result(
    call: &mut ExternCallContext,
    data_slot0: u64,
    data_slot1: u64,
    expected_rttid: u32,
    expected_vk: ValueKind,
) -> ExternResult {
    if expected_vk == ValueKind::Interface {
        call.ret_u64(0, data_slot0);
        call.ret_u64(1, data_slot1);
        call.ret_nil(2);
        call.ret_nil(3);
        return ExternResult::Ok;
    }

    // Unbox
    let actual_vk = interface::unpack_value_kind(data_slot0);
    let actual_rttid = interface::unpack_rttid(data_slot0);

    if expected_rttid != 0 && actual_rttid != expected_rttid {
        return write_get_error(call, DynErr::TypeMismatch, "type assertion failed");
    }

    let expected_slots = call.get_type_slot_count(expected_rttid) as usize;

    if expected_slots <= 2 {
        if actual_vk == ValueKind::Struct || actual_vk == ValueKind::Array {
            let data_ref = data_slot1 as GcRef;
            if data_ref.is_null() {
                call.ret_u64(0, 0);
                call.ret_u64(1, 0);
            } else {
                call.ret_u64(0, unsafe { Gc::read_slot(data_ref, 0) });
                call.ret_u64(
                    1,
                    if expected_slots > 1 {
                        unsafe { Gc::read_slot(data_ref, 1) }
                    } else {
                        0
                    },
                );
            }
        } else {
            call.ret_u64(0, data_slot1);
            call.ret_u64(1, 0);
        }
    } else {
        call.ret_u64(0, 0);
        call.ret_u64(1, data_slot1);
    }

    call.ret_nil(2);
    call.ret_nil(3);
    ExternResult::Ok
}

fn write_get_error(call: &mut ExternCallContext, err: DynErr, msg: &str) -> ExternResult {
    call.ret_u64(0, 0);
    call.ret_u64(1, 0);
    let (cause0, cause1) = dyn_sentinel_error(call, err.into());
    let (slot0, slot1) = create_error_with_cause(call, msg, cause0, cause1);
    call.ret_u64(2, slot0);
    call.ret_u64(3, slot1);
    ExternResult::Ok
}

fn write_set_error(call: &mut ExternCallContext, err: DynErr, msg: &str) -> ExternResult {
    let (cause0, cause1) = dyn_sentinel_error(call, err.into());
    let (slot0, slot1) = create_error_with_cause(call, msg, cause0, cause1);
    call.ret_u64(0, slot0);
    call.ret_u64(1, slot1);
    ExternResult::Ok
}

// ============================================================================
// Layer 7: User API (dyn.GetAttr etc)
// ============================================================================

fn dyn_get_attr(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let name_ref = call.arg_ref(2);

    if interface::is_nil(base_slot0) {
        return write_get_error(call, DynErr::NilBase, "cannot access field on nil");
    }

    let field_name = if name_ref.is_null() {
        return write_get_error(call, DynErr::NilBase, "field name is nil");
    } else {
        str_obj::as_str(name_ref)
    };

    match get_value(call, base_slot0, base_slot1, DynKey::Field(field_name)) {
        Ok((v0, v1)) => {
            call.ret_u64(0, v0);
            call.ret_u64(1, v1);
            call.ret_nil(2);
            call.ret_nil(3);
            ExternResult::Ok
        }
        Err(DynOrSuspend::Dyn(e, m)) => write_get_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_get_index(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let key_slot0 = call.arg_u64(2);
    let key_slot1 = call.arg_u64(3);

    if interface::is_nil(base_slot0) {
        return write_get_error(call, DynErr::NilBase, "cannot index nil");
    }

    match get_value(
        call,
        base_slot0,
        base_slot1,
        DynKey::Index(key_slot0, key_slot1),
    ) {
        Ok((v0, v1)) => {
            call.ret_u64(0, v0);
            call.ret_u64(1, v1);
            call.ret_nil(2);
            call.ret_nil(3);
            ExternResult::Ok
        }
        Err(DynOrSuspend::Dyn(e, m)) => write_get_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_set_attr(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let name_ref = call.arg_ref(2);
    let val_slot0 = call.arg_u64(3);
    let val_slot1 = call.arg_u64(4);

    if interface::is_nil(base_slot0) {
        return write_set_error(call, DynErr::NilBase, "cannot set field on nil");
    }

    let field_name = if name_ref.is_null() {
        return write_set_error(call, DynErr::NilBase, "field name is nil");
    } else {
        str_obj::as_str(name_ref)
    };

    match set_value(
        call,
        base_slot0,
        base_slot1,
        DynKey::Field(field_name),
        val_slot0,
        val_slot1,
    ) {
        Ok(()) => {
            call.ret_nil(0);
            call.ret_nil(1);
            ExternResult::Ok
        }
        Err(DynOrSuspend::Dyn(e, m)) => write_set_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

fn dyn_set_index(call: &mut ExternCallContext) -> ExternResult {
    let base_slot0 = call.arg_u64(0);
    let base_slot1 = call.arg_u64(1);
    let key_slot0 = call.arg_u64(2);
    let key_slot1 = call.arg_u64(3);
    let val_slot0 = call.arg_u64(4);
    let val_slot1 = call.arg_u64(5);

    if interface::is_nil(base_slot0) {
        return write_set_error(call, DynErr::NilBase, "cannot set index on nil");
    }

    match set_value(
        call,
        base_slot0,
        base_slot1,
        DynKey::Index(key_slot0, key_slot1),
        val_slot0,
        val_slot1,
    ) {
        Ok(()) => {
            call.ret_nil(0);
            call.ret_nil(1);
            ExternResult::Ok
        }
        Err(DynOrSuspend::Dyn(e, m)) => write_set_error(call, e, m.borrow()),
        Err(DynOrSuspend::Suspend(r)) => r,
    }
}

// ============================================================================
// Layer 7a: dyn_pack_any_slice (used by codegen)
// ============================================================================

fn dyn_pack_any_slice(call: &mut ExternCallContext) -> ExternResult {
    use vo_common_core::types::ValueMeta;

    let arg_count = call.arg_u64(0) as usize;
    let spread_flag = call.arg_u64(1) != 0;
    let args_start = 2u16;

    let mut spread_len = 0usize;
    let mut spread_slice_ref: GcRef = core::ptr::null_mut();
    let mut spread_elem_rttid = 0u32;
    let mut spread_elem_vk = ValueKind::Void;
    let mut spread_is_any = false;

    if spread_flag && arg_count > 0 {
        let last_idx = arg_count - 1;
        let last_slot0 = call.arg_u64(args_start + (last_idx * 2) as u16);
        let last_slot1 = call.arg_u64(args_start + (last_idx * 2) as u16 + 1);
        let last_vk = interface::unpack_value_kind(last_slot0);
        if last_vk != ValueKind::Slice {
            call.ret_ref(0, core::ptr::null_mut());
            let (cause0, cause1) = dyn_sentinel_error(call, DynErr::SigMismatch.into());
            let (slot0, slot1) =
                create_error_with_cause(call, "spread arg must be slice", cause0, cause1);
            call.ret_u64(1, slot0);
            call.ret_u64(2, slot1);
            return ExternResult::Ok;
        }

        let slice_rttid = interface::unpack_rttid(last_slot0);
        let elem = match call.get_slice_elem(slice_rttid) {
            Some(e) => e,
            None => {
                call.ret_ref(0, core::ptr::null_mut());
                let (cause0, cause1) = dyn_sentinel_error(call, DynErr::SigMismatch.into());
                let (slot0, slot1) =
                    create_error_with_cause(call, "invalid slice type", cause0, cause1);
                call.ret_u64(1, slot0);
                call.ret_u64(2, slot1);
                return ExternResult::Ok;
            }
        };

        spread_elem_rttid = elem.rttid();
        spread_elem_vk = elem.value_kind();
        spread_is_any = spread_elem_vk == ValueKind::Interface;

        spread_slice_ref = last_slot1 as GcRef;
        spread_len = if spread_slice_ref.is_null() {
            0
        } else {
            slice::len(spread_slice_ref)
        };
    }

    let out_len = if spread_flag && arg_count > 0 {
        (arg_count - 1) + spread_len
    } else {
        arg_count
    };
    let elem_meta = ValueMeta::new(0, ValueKind::Interface);
    let new_slice = slice::create(call.gc(), elem_meta, 16, out_len, out_len);

    if out_len > 0 {
        let dst_ptr = slice::data_ptr(new_slice) as *mut u64;
        let mut out_i = 0usize;
        let direct_count = if spread_flag && arg_count > 0 {
            arg_count - 1
        } else {
            arg_count
        };

        for i in 0..direct_count {
            let slot0 = call.arg_u64(args_start + (i * 2) as u16);
            let slot1 = call.arg_u64(args_start + (i * 2) as u16 + 1);
            unsafe {
                *dst_ptr.add(out_i * 2) = slot0;
                *dst_ptr.add(out_i * 2 + 1) = slot1;
            }
            out_i += 1;
        }

        if spread_flag && arg_count > 0 && !spread_slice_ref.is_null() {
            let spread_elem_bytes = array::elem_bytes(slice::array_ref(spread_slice_ref));
            for i in 0..spread_len {
                let (elem_slot0, elem_slot1) = if spread_is_any {
                    read_slice_elem(spread_slice_ref, i, spread_elem_bytes)
                } else {
                    let spread_elem_vr = ValueRttid::new(spread_elem_rttid, spread_elem_vk);
                    let raw = match sequence_elem_raw_slots(
                        call,
                        spread_elem_vr,
                        spread_elem_vk,
                        spread_elem_bytes,
                        |dst| {
                            read_slice_elem_logical_slots(
                                spread_slice_ref,
                                i,
                                spread_elem_vk,
                                spread_elem_bytes,
                                dst,
                            )
                        },
                    ) {
                        Ok(raw) => raw,
                        Err((err, msg)) => {
                            call.ret_ref(0, core::ptr::null_mut());
                            let (cause0, cause1) = dyn_sentinel_error(call, err.into());
                            let (slot0, slot1) = create_error_with_cause(call, msg, cause0, cause1);
                            call.ret_u64(1, slot0);
                            call.ret_u64(2, slot1);
                            return ExternResult::Ok;
                        }
                    };
                    let boxed = call.box_to_interface(spread_elem_rttid, spread_elem_vk, &raw);
                    (boxed.slot0, boxed.slot1)
                };
                unsafe {
                    *dst_ptr.add(out_i * 2) = elem_slot0;
                    *dst_ptr.add(out_i * 2 + 1) = elem_slot1;
                }
                out_i += 1;
            }
        }
    }

    call.gc()
        .mark_allocated_for_scan(slice::array_ref(new_slice));
    call.ret_ref(0, new_slice);
    call.ret_nil(1);
    call.ret_nil(2);
    ExternResult::Ok
}

fn dyn_type_assert_error(call: &mut ExternCallContext) -> ExternResult {
    let expected_rttid = call.arg_u64(0) as u32;
    let expected_vk = call.arg_u64(1) as u8;
    let got_slot0 = call.arg_u64(2);

    let got_vk = interface::unpack_value_kind(got_slot0);
    let got_rttid = interface::unpack_rttid(got_slot0);

    let msg = format!(
        "type assertion failed: expected vk={} rttid={}, got vk={:?} rttid={}",
        expected_vk, expected_rttid, got_vk, got_rttid
    );
    write_set_error(call, DynErr::TypeMismatch, &msg)
}

// ============================================================================
// Registration
// ============================================================================

#[derive(Clone, Copy)]
struct DynamicExternEntry {
    name: &'static str,
    func: crate::ffi::ExternFn,
    effects: crate::bytecode::ExternEffects,
}

const REGISTERED_EXTERNS: &[DynamicExternEntry] = &[
    DynamicExternEntry {
        name: "dyn_getDynErrors",
        func: get_dyn_errors,
        effects: crate::bytecode::ExternEffects::NONE,
    },
    DynamicExternEntry {
        name: "dyn_field",
        func: dyn_field,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_index",
        func: dyn_index,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_set_field",
        func: dyn_set_field,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_set_index_unified",
        func: dyn_set_index_unified,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_call",
        func: dyn_call,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_method",
        func: dyn_method,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_pack_any_slice",
        func: dyn_pack_any_slice,
        effects: crate::bytecode::ExternEffects::NONE,
    },
    DynamicExternEntry {
        name: "dyn_type_assert_error",
        func: dyn_type_assert_error,
        effects: crate::bytecode::ExternEffects::NONE,
    },
    DynamicExternEntry {
        name: "dyn_GetAttr",
        func: dyn_get_attr,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_GetIndex",
        func: dyn_get_index,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_SetAttr",
        func: dyn_set_attr,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
    DynamicExternEntry {
        name: "dyn_SetIndex",
        func: dyn_set_index,
        effects: crate::bytecode::ExternEffects::MAY_CALL_CLOSURE_REPLAY,
    },
];

pub fn known_extern_allowed_effects(name: &str) -> Option<crate::bytecode::ExternEffects> {
    REGISTERED_EXTERNS
        .iter()
        .find(|entry| entry.name == name)
        .map(|entry| entry.effects)
}

pub fn register_externs(
    registry: &mut crate::ffi::ExternRegistry,
    externs: &[crate::bytecode::ExternDef],
) {
    for (id, def) in externs.iter().enumerate() {
        for entry in REGISTERED_EXTERNS {
            if def.name == entry.name {
                registry.register_builtin_with_effects(
                    id as u32,
                    entry.name,
                    entry.func,
                    entry.effects,
                );
                break;
            }
        }
    }
}

#[cfg(test)]
mod tests;
