[package]
name = "vo-jit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "JIT compiler for Vo bytecode using Cranelift"
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
vo-runtime = { path = "../vo-runtime" }
vo-common-core = { path = "../vo-common-core" }

# Cranelift JIT
cranelift-codegen = "0.134.3"
cranelift-frontend = "0.134.3"
cranelift-jit = "0.134.3"
cranelift-module = "0.134.3"
cranelift-native = "0.134.3"
region = "3.0"
