[package]
name = "vo-jit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "JIT compiler for Vo bytecode using Cranelift"
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
vo-runtime = { path = "../vo-runtime" }
vo-common-core = { path = "../vo-common-core" }

# Cranelift JIT
cranelift-codegen = { version = "0.134.3", features = ["all-native-arch"] }
cranelift-frontend = "0.134.3"
cranelift-jit = "0.134.3"
cranelift-module = "0.134.3"
cranelift-native = "0.134.3"
cranelift-object = "0.134.3"
region = "3.0"
target-lexicon = "=0.13.5"

[dev-dependencies]
object = { version = "0.39.1", default-features = false, features = ["read"] }
