//! Regenerate the browser AOT host's pinned Unicode 16 lookup tables.
//!
//! Run from the repository root:
//! `cargo run -p vo-stdlib --example generate_web_unicode --features std -- lang/crates/vo-web/js/unicode16.ts`

use std::fmt::Write as _;
use std::path::PathBuf;

use icu_casemap::CaseMapper;
use icu_properties::props::{GeneralCategory, WhiteSpace};
use icu_properties::{CodePointMapData, CodePointSetData};
use regex_syntax::hir::{ClassUnicode, ClassUnicodeRange};

fn simple_fold(c: char) -> char {
    match c {
        'A'..='Z' => return char::from_u32(u32::from(c) + 0x20).unwrap_or(c),
        'a'..='z' => {
            return match c {
                'k' => '\u{212A}',
                's' => '\u{017F}',
                _ => char::from_u32(u32::from(c) - 0x20).unwrap_or(c),
            };
        }
        '\0'..='\u{7F}' => return c,
        _ => {}
    }
    let mut equivalents = ClassUnicode::new([ClassUnicodeRange::new(c, c)]);
    if equivalents.try_case_fold_simple().is_err() {
        return c;
    }
    let mut first = None;
    for range in equivalents.iter() {
        first.get_or_insert(range.start());
        if c < range.start() {
            return range.start();
        }
        if range.start() <= c && c < range.end() {
            return char::from_u32(u32::from(c) + 1).unwrap_or(c);
        }
    }
    first.unwrap_or(c)
}

fn mapping_ranges(map: impl Fn(char) -> char) -> Vec<(u32, u32, i32)> {
    let mut ranges = Vec::new();
    let mut active: Option<(u32, u32, i32)> = None;
    for input in 0..=char::MAX as u32 {
        let Some(character) = char::from_u32(input) else {
            continue;
        };
        let output = u32::from(map(character));
        if output == input {
            if let Some(range) = active.take() {
                ranges.push(range);
            }
            continue;
        }
        let delta = i64::from(output) - i64::from(input);
        let delta = i32::try_from(delta).expect("Unicode scalar delta must fit i32");
        match active {
            Some((start, end, previous_delta)) if end + 1 == input && previous_delta == delta => {
                active = Some((start, input, delta));
            }
            Some(range) => {
                ranges.push(range);
                active = Some((input, input, delta));
            }
            None => active = Some((input, input, delta)),
        }
    }
    if let Some(range) = active {
        ranges.push(range);
    }
    ranges
}

fn write_table(output: &mut String, name: &str, rows: impl IntoIterator<Item = (u32, u32, i32)>) {
    writeln!(output, "export const {name}: readonly UnicodeRange[] = [").unwrap();
    for (start, end, value) in rows {
        writeln!(output, "  [0x{start:x}, 0x{end:x}, {value}],").unwrap();
    }
    output.push_str("];\n\n");
}

fn main() {
    let destination = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .expect("expected one unicode16.ts destination path");
    assert_eq!(
        destination.file_name().and_then(|name| name.to_str()),
        Some("unicode16.ts"),
        "refusing to overwrite a path not named unicode16.ts"
    );

    let mut output = String::from(
        "// Generated by vo-stdlib/examples/generate_web_unicode.rs.\n\
         // Unicode semantics are pinned to Unicode 16.0. Do not edit manually.\n\n\
         export type UnicodeRange = readonly [start: number, end: number, value: number];\n\n",
    );
    write_table(
        &mut output,
        "GENERAL_CATEGORY",
        CodePointMapData::<GeneralCategory>::new()
            .iter_ranges()
            .map(|entry| (*entry.range.start(), *entry.range.end(), entry.value as i32)),
    );
    write_table(
        &mut output,
        "WHITE_SPACE",
        CodePointSetData::new::<WhiteSpace>()
            .iter_ranges()
            .map(|range| (*range.start(), *range.end(), 1)),
    );

    let mapper = CaseMapper::new();
    write_table(
        &mut output,
        "SIMPLE_LOWER",
        mapping_ranges(|character| mapper.simple_lowercase(character)),
    );
    write_table(
        &mut output,
        "SIMPLE_UPPER",
        mapping_ranges(|character| mapper.simple_uppercase(character)),
    );
    write_table(
        &mut output,
        "SIMPLE_TITLE",
        mapping_ranges(|character| mapper.simple_titlecase(character)),
    );
    write_table(&mut output, "SIMPLE_FOLD", mapping_ranges(simple_fold));

    std::fs::write(&destination, output).expect("failed to write Unicode table");
    eprintln!("generated {}", destination.display());
}
