version = 1

[repo]
name = "volang"
module = "github.com/vo-lang/volang"

[[first_party]]
name = "vogui"
repository = "vo-lang/vogui"
local_hint = "../vogui"
expected_commit = "0be8cd1b8abab4aabd510b6e2b9f74510f27f837"
ci_checkout = true

[[first_party.workspace]]
name = "js"
kind = "node"
path = "js"

[[first_party]]
name = "voplay"
repository = "vo-lang/voplay"
local_hint = "../voplay"
expected_commit = "2373af2320baed79521a6f0c57e9f19b77151c46"
ci_checkout = true

[[first_party]]
name = "vopack"
repository = "vo-lang/vopack"
local_hint = "../vopack"
expected_commit = "63a82992d8b75bbf9e5d0267e8ad6e8ad0c01bb8"
ci_checkout = true

[[first_party]]
name = "vostore"
repository = "vo-lang/vostore"
local_hint = "../vostore"
expected_commit = "ea5ad45b3893282b70852ea7b00fdc78c35fb454"
ci_checkout = true

[[external_project]]
name = "BlockKart"
repository = "vo-lang/BlockKart"
local_hint = "../BlockKart"
expected_commit = "49498844a61f081ea5bf6bd6687ffb9cfd35786c"
ci_checkout = true
