version = 1

[repo]
name = "volang"
module = "github.com/vo-lang/volang"

[[first_party]]
name = "vogui"
repository = "vo-lang/vogui"
local_hint = "../vogui"
expected_commit = "0be8cd1b8abab4aabd510b6e2b9f74510f27f837"
ci_checkout = true

[[first_party.workspace]]
name = "js"
kind = "node"
path = "js"

[[first_party]]
name = "voplay"
repository = "vo-lang/voplay"
local_hint = "../voplay"
expected_commit = "c5b9cfa6e955d0365da3ba000cdb583728df8fff"
ci_checkout = true

[[first_party]]
name = "vopack"
repository = "vo-lang/vopack"
local_hint = "../vopack"
expected_commit = "63a82992d8b75bbf9e5d0267e8ad6e8ad0c01bb8"
ci_checkout = true

[[first_party]]
name = "vostore"
repository = "vo-lang/vostore"
local_hint = "../vostore"
expected_commit = "ea5ad45b3893282b70852ea7b00fdc78c35fb454"
ci_checkout = true

[[external_project]]
name = "BlockKart"
repository = "vo-lang/BlockKart"
local_hint = "../BlockKart"
expected_commit = "a2978709920bb9b62078ca9563246cc581603076"
ci_checkout = true
