#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vo_binary="${VO_UI_BIN:-$repo_root/target/debug/vo}"
gallery="$repo_root/ui/showcases/component-gallery"
snapshot="$(mktemp "${TMPDIR:-/tmp}/volang-uikit-gallery.XXXXXX")"
trap 'rm -f "$snapshot"' EXIT

actions=(
  "--input=Component search=runtime"
  "--key=Component search=Enter"
  "--wait-text=Search submitted: runtime"
  "--click=Clear Component search"
  "--wait-text=Component search cleared"
  "--click=Increase Build replicas"
  "--wait-text=Build replica count changed"
  "--click=Desktop"
  "--wait-text=Preview target: desktop"
  "--click=Renderer"
  "--wait-text=Selected foundation package: renderer"
  "--click=Remove Stable"
  "--wait-text=Stable tag removed"
  "--click=Resolve package"
  "--wait-text=Package resolved"
  "--click=More Product navigation"
  "--wait-text=Metrics"
  "--click=Compact"
  "--wait-text=Navigation layout: compact"
  "--input=Framework package=run"
  "--key=Framework package=Enter"
  "--wait-text=Framework package: runtime"
  "--input=Release platforms=desk"
  "--key=Release platforms=Enter"
  "--wait-text=Release platform changed: desktop"
  "--click=Remove Desktop target"
  "--wait-text=Release platform changed: desktop"
  "--input=Release date=30/08/2026"
  "--key=Release date=Enter"
  "--wait-text=Release date: 2026-08-30"
  "--click=Release window 2026-08-21"
  "--wait-text=Release window date: 2026-08-21"
  "--click=Cancel app.wasm"
  "--wait-text=Upload cancelled: bundle"
  "--click=Retry app.wasm"
  "--wait-text=Upload retried: bundle"
  "--key=Project canvas=ContextMenu"
  "--wait-text=View options"
  "--click=View options"
  "--wait-text=Compact view"
  "--click=Compact view"
  "--wait-text=Context action: compact"
  "--key=Bold=ArrowRight"
  "--click=Italic"
  "--wait-text=Text style changed: italic"
  "--click=Framework quality, 5 of 5 stars"
  "--wait-text=Framework quality changed"
  "--key=Inspector size=ArrowRight"
  "--wait-text=Inspector size changed"
  "--click=Next, Compiler"
  "--wait-text=Carousel item: runtime"
  "--input=Release notes=AOT contract text"
  "--click=+  Release targets"
  "--wait-text=The same UIKit tree renders on Web and desktop."
  "--click=Open drawer"
  "--wait-text=Release inspector"
  "--key=Release inspector=Escape"
  "--wait-absent-text=Release inspector"
  "--click=Show toast"
  "--wait-text=Release ready"
  "--click=Dismiss"
  "--wait-absent-text=Release ready"
  "--click=Open commands"
  "--input=Command palette query=publish"
  "--key=Command palette query=Enter"
  "--wait-text=Command executed: release.publish"
  "--wait-absent-text=Build verified WebAssembly and desktop AOT artifacts"
  "--click=Open commands"
  "--click=Run project"
  "--wait-text=Command executed: run.start"
  "--wait-absent-text=Create a typed Volang workspace"
  "--click=Open commands"
  "--key=Open file=Escape"
  "--wait-absent-text=Create a typed Volang workspace"
  "--click=Open commands"
  "--key=Command palette query=Escape"
  "--wait-absent-text=Create a typed Volang workspace"
)

"$vo_binary" ui test "$gallery" --mode=vm \
  "${actions[@]}" --snapshot="$snapshot" --update
"$vo_binary" ui test "$gallery" --mode=jit \
  "${actions[@]}" --snapshot="$snapshot"
