use icu_casemap::CaseMapperBorrowed;
use sha2::{Digest, Sha256};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io::{self, Write as _};
use std::process::ExitCode;
use vo_common::identifier::{
    is_identifier_continue, is_identifier_start, is_unicode_control, is_unicode_white_space,
    UNICODE_PROFILE_VERSION,
};

const ICU_CASEMAP_VERSION: &str = "2.0.1";

#[derive(Debug)]
struct Mapping {
    source: u32,
    folded: Vec<u32>,
}

#[derive(Debug)]
struct Range {
    start: u32,
    end: u32,
    step: u32,
    delta: i64,
}

#[derive(Debug)]
struct CodePointRange {
    start: u32,
    end: u32,
}

fn main() -> ExitCode {
    let generated = generate();
    let mut args = env::args_os().skip(1);
    match (args.next(), args.next(), args.next()) {
        (None, None, None) => {
            if let Err(error) = io::stdout().write_all(generated.as_bytes()) {
                eprintln!("failed to write generated case-fold data: {error}");
                return ExitCode::FAILURE;
            }
        }
        (Some(flag), Some(path), None) if flag == "--check" => match fs::read_to_string(&path) {
            Ok(current) if current == generated => {}
            Ok(_) => {
                eprintln!(
                    "generated Unicode case-fold data differs from {}",
                    path.to_string_lossy()
                );
                return ExitCode::FAILURE;
            }
            Err(error) => {
                eprintln!(
                    "failed to read Unicode case-fold data {}: {error}",
                    path.to_string_lossy()
                );
                return ExitCode::FAILURE;
            }
        },
        (Some(flag), Some(path), None) if flag == "--write" => {
            if let Err(error) = fs::write(&path, generated) {
                eprintln!(
                    "failed to write Unicode authority data {}: {error}",
                    path.to_string_lossy()
                );
                return ExitCode::FAILURE;
            }
        }
        _ => {
            eprintln!(
                "usage: generate_unicode_casefold_data [--check|--write scripts/ci/unicode_casefold_data.mjs]"
            );
            return ExitCode::FAILURE;
        }
    }
    ExitCode::SUCCESS
}

fn generate() -> String {
    let mappings = collect_mappings();
    let digest = mapping_digest(&mappings);
    let (ranges, exceptions) = compress_mappings(&mappings);
    let alphabetic =
        collect_property_ranges(|character| character != '_' && is_identifier_start(character));
    let alnum =
        collect_property_ranges(|character| character != '_' && is_identifier_continue(character));
    let white_space = collect_property_ranges(is_unicode_white_space);
    let control = collect_property_ranges(is_unicode_control);
    let property_digest = property_digest(&[
        ("Alphabetic", &alphabetic),
        ("Alnum", &alnum),
        ("White_Space", &white_space),
        ("General_Category_Control", &control),
    ]);

    let mut output = String::new();
    writeln!(
        output,
        "// @generated by `cargo run -q -p vo-module --example generate_unicode_casefold_data`."
    )
    .unwrap();
    writeln!(
        output,
        "// Default, locale-independent full case folding from ICU4X {ICU_CASEMAP_VERSION} / Unicode {UNICODE_PROFILE_VERSION}."
    )
    .unwrap();
    writeln!(output, "// Mapping SHA-256: {digest}").unwrap();
    writeln!(output, "// Do not edit by hand.\n").unwrap();
    writeln!(
        output,
        "export const UNICODE_CASE_FOLD_VERSION = {UNICODE_PROFILE_VERSION:?};"
    )
    .unwrap();
    writeln!(
        output,
        "export const ICU_CASEMAP_VERSION = {ICU_CASEMAP_VERSION:?};"
    )
    .unwrap();
    writeln!(
        output,
        "export const UNICODE_CASE_FOLD_MAPPING_COUNT = {};",
        mappings.len()
    )
    .unwrap();
    writeln!(
        output,
        "export const UNICODE_CASE_FOLD_MAPPING_SHA256 = {digest:?};\n"
    )
    .unwrap();

    writeln!(
        output,
        "// Flat tuples: source start, source end, stride, target-minus-source delta."
    )
    .unwrap();
    writeln!(
        output,
        "export const UNICODE_CASE_FOLD_RANGES = Object.freeze(["
    )
    .unwrap();
    for range in &ranges {
        writeln!(
            output,
            "  0x{:X}, 0x{:X}, {}, {},",
            range.start, range.end, range.step, range.delta
        )
        .unwrap();
    }
    writeln!(output, "]);\n").unwrap();

    writeln!(output, "// Flat tuples: source scalar, full folded string.").unwrap();
    writeln!(
        output,
        "export const UNICODE_CASE_FOLD_EXCEPTIONS = Object.freeze(["
    )
    .unwrap();
    for mapping in &exceptions {
        writeln!(
            output,
            "  0x{:X}, {},",
            mapping.source,
            javascript_string(&mapping.folded)
        )
        .unwrap();
    }
    writeln!(output, "]);\n").unwrap();

    writeln!(
        output,
        "// Pinned Unicode properties consumed by JS protocol validators and generated"
    )
    .unwrap();
    writeln!(
        output,
        "// from the same vo-common-core authority used by the lexer and extern keys."
    )
    .unwrap();
    writeln!(
        output,
        "export const UNICODE_PROPERTY_DATA_VERSION = {UNICODE_PROFILE_VERSION:?};"
    )
    .unwrap();
    writeln!(
        output,
        "export const UNICODE_PROPERTY_DATA_SHA256 = {property_digest:?};\n"
    )
    .unwrap();
    write_property_ranges(&mut output, "UNICODE_ALPHABETIC_RANGES", &alphabetic);
    output.push('\n');
    write_property_ranges(&mut output, "UNICODE_ALNUM_RANGES", &alnum);
    output.push('\n');
    write_property_ranges(&mut output, "UNICODE_WHITE_SPACE_RANGES", &white_space);
    output.push('\n');
    write_property_ranges(&mut output, "UNICODE_CONTROL_RANGES", &control);
    output
}

fn collect_property_ranges(predicate: impl Fn(char) -> bool) -> Vec<CodePointRange> {
    let mut ranges = Vec::new();
    let mut open: Option<CodePointRange> = None;
    for source in 0..=char::MAX as u32 {
        let accepted = char::from_u32(source).is_some_and(&predicate);
        match (&mut open, accepted) {
            (None, true) => {
                open = Some(CodePointRange {
                    start: source,
                    end: source,
                })
            }
            (Some(range), true) => range.end = source,
            (Some(_), false) => ranges.push(open.take().unwrap()),
            (None, false) => {}
        }
    }
    if let Some(range) = open {
        ranges.push(range);
    }
    ranges
}

fn property_digest(properties: &[(&str, &[CodePointRange])]) -> String {
    let mut hasher = Sha256::new();
    for (name, ranges) in properties {
        hasher.update(name.as_bytes());
        hasher.update([0]);
        for range in *ranges {
            hasher.update(range.start.to_be_bytes());
            hasher.update(range.end.to_be_bytes());
        }
    }
    format!("{:x}", hasher.finalize())
}

fn write_property_ranges(output: &mut String, name: &str, ranges: &[CodePointRange]) {
    writeln!(output, "// Flat inclusive start/end tuples.").unwrap();
    writeln!(output, "export const {name} = Object.freeze([").unwrap();
    for range in ranges {
        writeln!(output, "  0x{:X}, 0x{:X},", range.start, range.end).unwrap();
    }
    writeln!(output, "]);").unwrap();
}

fn collect_mappings() -> Vec<Mapping> {
    let mapper = CaseMapperBorrowed::new();
    let mut mappings = Vec::new();
    for source in 0..=char::MAX as u32 {
        let Some(character) = char::from_u32(source) else {
            continue;
        };
        let mut encoded = [0_u8; 4];
        let original = character.encode_utf8(&mut encoded);
        let folded = mapper.fold_string(original);
        if folded.as_ref() != original {
            mappings.push(Mapping {
                source,
                folded: folded.chars().map(u32::from).collect(),
            });
        }
    }
    mappings
}

fn compress_mappings(mappings: &[Mapping]) -> (Vec<Range>, Vec<&Mapping>) {
    let mut ranges = Vec::new();
    let mut exceptions = Vec::new();
    let mut index = 0;

    while index < mappings.len() {
        let mapping = &mappings[index];
        let Some(&target) = mapping.folded.first().filter(|_| mapping.folded.len() == 1) else {
            exceptions.push(mapping);
            index += 1;
            continue;
        };
        let delta = i64::from(target) - i64::from(mapping.source);
        if index + 1 >= mappings.len() {
            exceptions.push(mapping);
            index += 1;
            continue;
        }
        let next = &mappings[index + 1];
        let Some(&next_target) = next.folded.first().filter(|_| next.folded.len() == 1) else {
            exceptions.push(mapping);
            index += 1;
            continue;
        };
        let step = next.source - mapping.source;
        if i64::from(next_target) - i64::from(next.source) != delta {
            exceptions.push(mapping);
            index += 1;
            continue;
        }

        let mut end = index + 2;
        while let Some(candidate) = mappings.get(end) {
            let previous = &mappings[end - 1];
            let Some(&candidate_target) = candidate
                .folded
                .first()
                .filter(|_| candidate.folded.len() == 1)
            else {
                break;
            };
            if candidate.source - previous.source != step
                || i64::from(candidate_target) - i64::from(candidate.source) != delta
            {
                break;
            }
            end += 1;
        }

        if end - index >= 3 {
            ranges.push(Range {
                start: mapping.source,
                end: mappings[end - 1].source,
                step,
                delta,
            });
            index = end;
        } else {
            exceptions.push(mapping);
            index += 1;
        }
    }

    (ranges, exceptions)
}

fn mapping_digest(mappings: &[Mapping]) -> String {
    let mut hasher = Sha256::new();
    for mapping in mappings {
        let mut line = format!("{:06X}\t", mapping.source);
        for (index, target) in mapping.folded.iter().enumerate() {
            if index > 0 {
                line.push(' ');
            }
            write!(line, "{target:06X}").unwrap();
        }
        line.push('\n');
        hasher.update(line.as_bytes());
    }
    format!("{:x}", hasher.finalize())
}

fn javascript_string(scalars: &[u32]) -> String {
    let mut output = String::from("\"");
    for &scalar in scalars {
        match scalar {
            0x20..=0x21 | 0x23..=0x5b | 0x5d..=0x7e => {
                output.push(char::from_u32(scalar).unwrap());
            }
            0x22 => output.push_str("\\\""),
            0x5c => output.push_str("\\\\"),
            _ => write!(output, "\\u{{{scalar:X}}}").unwrap(),
        }
    }
    output.push('"');
    output
}
