[package]
name = "vo-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Lexer, AST definitions, and parser for the Vo programming language"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
publish = ["crates-io"]

[dependencies]
vo-common = { workspace = true, default-features = false }

[features]
default = []
serde = ["vo-common/serde"]
