import {readFile, writeFile} from 'node:fs/promises';

const directory = new URL('./', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('package.json', directory)));
// Refuse a partial distribution before npm calculates archive membership.
for (const entry of Object.values(manifest.exports)) {
  for (const path of [entry.import, entry.types]) await readFile(new URL(path, directory));
}
for (const path of ['pkg/vo_web_bg.wasm']) {
  await readFile(new URL(path, directory));
}
// wasm-pack writes a nested .gitignore containing '*'. npm otherwise uses that
// rule even when the parent package explicitly includes these directories.
// An empty npm ignore file keeps all generated bindings, snippets and licenses.
for (const name of ['pkg']) {
  await writeFile(new URL(name + '/.npmignore', directory), '# Generated by prepare-package.mjs for npm archive delivery.\n');
}
