//! Host capability bridge for native extensions.
//!
//! The host (e.g. studio-native) builds a [`HostBridge`] with the capabilities
//! it provides and calls [`install`] before running the guest VM.  Extensions
//! access host capabilities through the submodule APIs:
//!
//! - [`timer`] — timeout and interval scheduling
//! - [`tick`] — game/animation tick loops
//! - [`capability`] — capability queries
//!
//! The bridge is thread-local so concurrent guest VM sessions never interfere.
//!
//! ## Cross-dylib injection
//!
//! When extensions are loaded via dlopen with RTLD_LOCAL, each dylib gets its
//! own copy of the BRIDGE thread-local.  After loading, the extension loader
//! calls `vo_ext_set_host_bridge` (generated by [`export_extensions!`]) with a
//! raw pointer to the host's bridge.  The dylib stores it as a borrowed
//! reference.  The host **must** call `vo_ext_clear_host_bridge` before
//! dropping the bridge.

pub mod capability;
pub mod tick;
pub mod timer;

use std::cell::RefCell;

/// Central host bridge that holds all registered capabilities.
///
/// Constructed via the builder pattern:
/// ```ignore
/// let bridge = HostBridge::new()
///     .with_capability("render_island_host")
///     .with_tick(Box::new(my_tick_provider));
/// vo_ext::host::install(bridge);
/// ```
pub struct HostBridge {
    pub(crate) timer: Option<Box<dyn timer::TimerProvider>>,
    pub(crate) tick: Option<Box<dyn tick::TickProvider>>,
    pub(crate) capabilities: Vec<String>,
}

impl Default for HostBridge {
    fn default() -> Self {
        Self::new()
    }
}

impl HostBridge {
    pub fn new() -> Self {
        Self {
            timer: None,
            tick: None,
            capabilities: Vec::new(),
        }
    }

    pub fn with_timer(mut self, provider: Box<dyn timer::TimerProvider>) -> Self {
        self.timer = Some(provider);
        self
    }

    pub fn with_tick(mut self, provider: Box<dyn tick::TickProvider>) -> Self {
        self.tick = Some(provider);
        self
    }

    pub fn with_capability(mut self, name: impl Into<String>) -> Self {
        self.capabilities.push(name.into());
        self
    }
}

enum BridgeSlot {
    Owned(Box<HostBridge>),
    Borrowed(*const HostBridge),
}

// Safety: Borrowed points to a HostBridge whose providers are Send+Sync.
// The host must keep it alive until receive_clear_host_bridge is called.
unsafe impl Send for BridgeSlot {}
unsafe impl Sync for BridgeSlot {}

thread_local! {
    static BRIDGE: RefCell<Option<BridgeSlot>> =
        const { RefCell::new(None) };
}

/// Install a host bridge for the current thread.
pub fn install(bridge: HostBridge) {
    BRIDGE.with(|slot| {
        *slot.borrow_mut() = Some(BridgeSlot::Owned(Box::new(bridge)));
    });
}

/// Clear the host bridge for the current thread.
pub fn clear() {
    BRIDGE.with(|slot| {
        *slot.borrow_mut() = None;
    });
}

/// Execute a closure with the current thread's host bridge, if any.
pub fn with_bridge<F, R>(f: F) -> Option<R>
where
    F: FnOnce(&HostBridge) -> R,
{
    BRIDGE.with(|slot| {
        let borrow = slot.borrow();
        match borrow.as_ref() {
            Some(BridgeSlot::Owned(bridge)) => Some(f(bridge.as_ref())),
            Some(BridgeSlot::Borrowed(ptr)) => Some(f(unsafe { &**ptr })),
            None => None,
        }
    })
}

// =============================================================================
// Cross-dylib injection helpers
// =============================================================================

/// Encode a pointer to the host's bridge for transmission over C ABI.
///
/// The returned `usize` is a raw `*const HostBridge`.  It remains valid as
/// long as the bridge is installed (i.e. until [`clear`] is called).
pub fn encode_bridge_ptr(bridge: &HostBridge) -> usize {
    bridge as *const HostBridge as usize
}

/// Receive a host bridge pointer from the extension loader.
///
/// # Safety
///
/// `ptr` must come from [`encode_bridge_ptr`] and the bridge must remain
/// alive until [`receive_clear_host_bridge`] is called.
pub unsafe fn receive_host_bridge(ptr: usize) {
    let raw = ptr as *const HostBridge;
    BRIDGE.with(|slot| {
        *slot.borrow_mut() = Some(BridgeSlot::Borrowed(raw));
    });
}

/// Clear the dylib-side bridge reference.  Called before the host drops
/// its bridge to avoid dangling pointers.
pub fn receive_clear_host_bridge() {
    BRIDGE.with(|slot| {
        *slot.borrow_mut() = None;
    });
}
