[package]
name = "vo-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Bytecode generation for the Vo compiler"
repository.workspace = true
homepage.workspace = true
publish = false

[features]
compiler-profile = ["vo-common/compiler-profile", "vo-analysis/compiler-profile"]

[dependencies]
vo-common = { path = "../vo-common", default-features = false }
vo-common-core = { path = "../vo-common-core" }
vo-syntax = { path = "../vo-syntax" }
vo-analysis = { path = "../vo-analysis" }

[dev-dependencies]
vo-ffi-macro.workspace = true
vo-runtime = { path = "../vo-runtime" }
vo-vm = { path = "../vo-vm" }
