use super::{compare, digest, document, quote, Catalog, LoadedPage};
use anyhow::{bail, Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

pub(super) const DIRECTORY: &str = "apps/studio/next/documentation";
pub(super) const ARTIFACT: &str = "studio-next-documentation.generated";

pub(super) fn materialize(
    catalog: &Catalog,
    pages: &[LoadedPage<'_>],
) -> Result<BTreeMap<String, Vec<u8>>> {
    // The released UI guide still documents the previous runtime. Its source
    // remains in the legacy product; the Web guides use this same generator.
    let mut selected: Vec<_> = pages
        .iter()
        .filter(|page| page.section.id != "ui")
        .collect();
    selected.sort_by_key(|page| page.section.id != "web-ui");
    let routes = selected
        .iter()
        .map(|page| (page.page.file.clone(), page.page.id.clone()))
        .collect();
    let mut files = BTreeMap::new();
    let mut metadata = vec![];
    let mut search_pages = vec![];
    let mut index = String::from("// Code generated by vo-dev from lang/docs/catalog.toml. DO NOT EDIT.\n\
        // Only chapter metadata is linked into Studio; bodies are separate JSON assets.\n\
        package documentation\n\n\
        type Page struct {\n\
        ID string\nTitle string\nSummary string\nSectionID string\nSection string\nSourcePath string\n\
        Asset string\nSHA256 string\nHeadingID string\n}\n\n");
    index.push_str(&format!(
        "func Version() string {{ return {} }}\n\n",
        quote(&catalog.version)
    ));
    index.push_str(&format!(
        "func PageCount() int {{ return {} }}\n\n",
        selected.len()
    ));
    index.push_str("func Pages() []Page {\nreturn []Page{\n");
    for loaded in selected {
        let document = document::parse(&loaded.markdown, &loaded.page.file, &routes)
            .with_context(|| format!("parse Studio document {}", loaded.page.file))?;
        search_pages.push(serde_json::json!({
            "ID": loaded.page.id,
            "Text": format!("{} {} {} {}", loaded.page.title, loaded.page.summary,
                loaded.section.title, document.search_text()).to_lowercase(),
        }));
        let bytes = serde_json::to_vec(&document)?;
        if bytes.len() > 2 * 1024 * 1024 {
            bail!(
                "Studio document {} exceeds 2 MiB of semantic JSON",
                loaded.page.id
            );
        }
        let file = format!("page-{}.json", loaded.page.id);
        let hash = digest(&bytes).trim_start_matches("sha256:").to_owned();
        index.push_str("{\n");
        let fields = [
            ("ID", loaded.page.id.as_str()),
            ("Title", &loaded.page.title),
            ("Summary", &loaded.page.summary),
            ("SectionID", &loaded.section.id),
            ("Section", &loaded.section.title),
            ("SourcePath", &loaded.page.file),
            ("Asset", &file),
            ("SHA256", &hash),
            ("HeadingID", &document.heading_id),
        ];
        metadata.push(
            fields
                .iter()
                .map(|(name, value)| (name.to_string(), value.to_string()))
                .collect::<BTreeMap<_, _>>(),
        );
        for (name, value) in fields {
            index.push_str(&format!("{name}: {},\n", quote(value)));
        }
        index.push_str("},\n");
        files.insert(file, bytes);
    }
    index.push_str("}\n}\n");
    let search = serde_json::to_vec(&serde_json::json!({"version": 1, "pages": search_pages}))?;
    if search.len() > 2 * 1024 * 1024 {
        bail!("Studio document search index exceeds 2 MiB");
    }
    let search_hash = digest(&search).trim_start_matches("sha256:").to_owned();
    index.push_str(&format!("\nfunc SearchAsset() string {{ return \"search.json\" }}\n\nfunc SearchSHA256() string {{ return {} }}\n", quote(&search_hash)));
    files.insert("search.json".into(), search);
    files.insert(
        "index.json".into(),
        serde_json::to_vec(&serde_json::json!({ "version": 1, "pages": metadata,
            "search": {"Asset": "search.json", "SHA256": search_hash} }))?,
    );
    files.insert(
        "catalog.vo".into(),
        vo_syntax::format_source(&index)
            .map_err(anyhow::Error::msg)?
            .into_bytes(),
    );
    if files.values().map(Vec::len).sum::<usize>() > 8 * 1024 * 1024 {
        bail!("Studio document assets exceed 8 MiB");
    }
    Ok(files)
}

// This closed generated directory owns the catalog, indexes, provenance and
// page-ID JSON files. Removed chapters retire their assets on regeneration.
pub(super) fn synchronize(
    root: &Path,
    files: &BTreeMap<String, Vec<u8>>,
    write: bool,
) -> Result<()> {
    let directory = root.join(DIRECTORY);
    if write {
        fs::create_dir_all(&directory)?;
    }
    let existing = fs::read_dir(&directory)
        .with_context(|| format!("read generated Studio documents {}", directory.display()))?;
    let mut obsolete = vec![];
    for entry in existing {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().into_owned();
        let page = name
            .strip_prefix("page-")
            .and_then(|name| name.strip_suffix(".json"));
        let owned = matches!(
            name.as_str(),
            "catalog.vo" | "index.json" | "search.json" | "provenance.json"
        ) || page.is_some_and(|id| {
            !id.is_empty()
                && id
                    .bytes()
                    .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
        });
        if !entry.file_type()?.is_file() || !owned {
            bail!(
                "unexpected generated Studio document: {}",
                entry.path().display()
            );
        }
        if !files.contains_key(&name) {
            if !write {
                bail!(
                    "stale generated Studio document: {}",
                    entry.path().display()
                );
            }
            obsolete.push(entry.path());
        }
    }
    for (name, bytes) in files {
        if write {
            fs::write(directory.join(name), bytes)?;
        } else {
            compare(root, &format!("{DIRECTORY}/{name}"), bytes)?;
        }
    }
    for path in obsolete {
        fs::remove_file(path)?;
    }
    Ok(())
}

#[cfg(test)]
mod search_tests {
    use super::*;
    use crate::generate_docs::{Page, Section};

    #[test]
    fn content_search_uses_selected_semantic_documents_and_their_exact_identity() {
        let catalog = Catalog {
            format: 1,
            version: "test".into(),
            section: vec![
                Section {
                    id: "web-ui".into(),
                    title: "Web UI".into(),
                    page: vec![Page {
                        id: "first-steps".into(),
                        title: "First steps".into(),
                        summary: "Build a component".into(),
                        file: "ui/next/guides/first-steps.md".into(),
                    }],
                },
                Section {
                    id: "ui".into(),
                    title: "Compatibility".into(),
                    page: vec![Page {
                        id: "old-ui".into(),
                        title: "Old UI".into(),
                        summary: "Earlier API".into(),
                        file: "ui/docs/old.md".into(),
                    }],
                },
            ],
        };
        let selected = &catalog.section[0];
        let legacy = &catalog.section[1];
        let pages = [
            LoadedPage {section: selected, page: &selected.page[0], markdown: "# Guide\n\nA **typed** component.\n\n```vo\nui.InspectProp(scope, \"name\", name)\n```\n\n中文\n".into()},
            LoadedPage {section: legacy, page: &legacy.page[0], markdown: "# Legacy\n\nRetiredSearchTerm\n".into()},
        ];
        let files = materialize(&catalog, &pages).unwrap();
        let index: serde_json::Value = serde_json::from_slice(&files["index.json"]).unwrap();
        let search: serde_json::Value = serde_json::from_slice(&files["search.json"]).unwrap();
        assert_eq!(search["version"], 1);
        assert_eq!(search["pages"].as_array().unwrap().len(), 1);
        assert_eq!(search["pages"][0]["ID"], "first-steps");
        let text = search["pages"][0]["Text"].as_str().unwrap();
        assert!(text.contains("a typed component."));
        assert!(
            text.contains("guide"),
            "the separately rendered first heading must be searchable"
        );
        assert!(text.contains("ui.inspectprop") && text.contains("中文"));
        assert!(!text.contains("retiredsearchterm"));
        assert_eq!(index["search"]["Asset"], "search.json");
        assert_eq!(
            index["search"]["SHA256"],
            digest(&files["search.json"]).trim_start_matches("sha256:")
        );
        assert!(std::str::from_utf8(&files["catalog.vo"])
            .unwrap()
            .contains("SearchSHA256"));
    }
}
